### ISSUE TITLE
Support various JADNC controller types

### ISSUE THREAD

**Issue by maurei** [json-api-dotnet/JsonApiDotNetCore#1052]
Currently the OpenApi integration only picks up on controllers that inherit from `JsonApiController`. This needs to be expanded so that the following are also picked up on:
- `JsonApiQueryController`
- `JsonApiCommandController`
-  Usages of `HttpRestrictAttribute`
-  Overrides of JsonApiController methods
- Handling of [HttpHead]

**Comment by bkoelman** [comment]
Upon further investigation, I found this isn't as simple as it sounds.

The difficulty lies in the fact that `JsonApiController<,>` exposes action methods for *all* endpoints, only to throw from the unexposed ones. This was done to provide a more informative error response instead of just 404.

This means we can't rely on whether an action method exist to determine whether to expose an endpoint in OAS. We can't rely on the constructor parameters (`IGetAllService`, etc) either, because an action method _may_ still be provided, containing logic that doesn't use the JsonApiDotNetCore pipeline.

As a compromise, I've ended up with the following:
1. When `[Resource(GenerateControllerEndpoints = ...)]` is used with a value _other_ than `None`, this means that auto-generated controllers are being used. All JSON:API endpoints not in the specified set are hidden.
   - To provide a custom implementation for a JSON:API endpoint in a partial class, the developer _must_ include that endpoint in `[Resource...]` for it to show up. This enables to still write custom endpoints that throw, which shouldn't be listed.
2. When using `[Resource(GenerateControllerEndpoints = None)]` or omitted at all, there _may_ be a hand-written controller or not. So we can't determine what to hide. Code higher in the stack looks at the signature of action methods. If it is recognized as a JSON:API endpoint, it gets listed.
   - This means that hand-written controllers should _only_ implement the endpoints it supports, for correct listing. This means deriving from `BaseJsonApiController` instead of `JsonApiController` and adding `[HttpGet]` etc on your action methods directly.

Non-standard action methods on JSON:API-controllers (for example, to upload a file) are out of scope. They remain hidden. The same applies for non-JSON:API controllers, and for atomic:operations controllers. Separate issues exist to address these.
