### ISSUE TITLE
Filtering on the basis of relationship tables not working.

### ISSUE THREAD

**Issue by rahultandial87** [json-api-dotnet/JsonApiDotNetCore#1071]
I am using jsonapidotnetcore version 4.1. 
I have the below data model and I am trying to use filter on the below models.

public class TicketMaster : Identifiable
{
    public int TicketID { get; set; }

    public string Description { get; set; }
    public string LastName { get; set; }

    [HasMany]
    public virtual ICollection<TicketStatus> Status { get; set; }
}

public class TicketStatus: Identifiable
{
    public int TicketStatusId{ get; set; }
    public int TicketId{ get; set; }
    public string Status { get; set; }
    public string UpdatedBy { get; set; }
    
    [HasOne]
    public virtual TicketMaster Ticket{ get; set; }
}

Ticket master contains unique records for each ticket. Once a ticket is created, a record adds into TicketMaster. For any activity performed on a ticket, a record gets inserted in TicketStatus.

For example:
TicketMaster has 20 records for 20 newly created tickets.
TicketStatus contains records for activities performed on each ticket. Like a ticket's initial status is Open, then it gets changed to  In Progress, Pending, Resolved. There will be an individual record for each activity performed on ticket in TicketStatus.  For wach ticket in Ticket Master, there can be more than 1 records in TIcketStatus.

WE want to fetch the tickets from TicketMaster whose status in TicketStaus is "In-Progress". 
We are trying using https://localhost/api/TicketMaster?include=TicketStatus&filter[TicketStatus]=equals(Equals,%27In Progress%27). It is not helping.

Instead of the filtered Tickets, we get first 10 tickets in TicketMaster with Relationship Data. irrespective of their status. I want Tickets on the basis of their relationship status. 

Kindly assist.

**Comment by bart-degreed** [comment]
This isn't possible using the data model you've chosen. I suggest storing the current status as a column in TicketMaster, then add a historic record to another table each time TicketMaster is updated.

**Comment by rachael-ross** [comment]
In version 4.2 we're achieving this with the new has() filter that accepts criteria.

**Comment by bart-degreed** [comment]
That wouldn't work. It requires a `max(id)` function to find the latest status in the to-many relationship.

But that's beside the point. It's bad practice to rely on IDs to determine order, because it is an implementation detail that's hard to control/correct manually (auto-generated, DB-server migrations, etc). Making it so hard (design-wise and performance-wise) to retrieve the current state is a flawed design in my opinion.

So I think this user is a bit lost and needs help from a peer with basic data modeling skills. Questions like: "What are you trying to accomplish?", "What queries do you expect you'll need?" etc. should be asked first, before designing the model. That's not my role and this is not the place to ask such questions.
