### ISSUE TITLE
Case insensitive contains filter

### ISSUE THREAD

**Issue by MehdiR-S** [json-api-dotnet/JsonApiDotNetCore#1133]
Hello.
I would like to have a case insensitive contains filter... I never took a lot of time to try to find a simple solution for this. JsonApiDotnetCore documentation's website is like not complete for this kind of thing... I tried to create a custom global filter but it's impossible, so I tried to do a custom filter for an entity and I didn't success... Seriously, for a simple thing like this that's not normal to take so much time...

Thanks

**Comment by MehdiR-S** [comment]
By the way I'm using .NET Core 3.1 and JsonApiDotNetCore 4.2.0

**Comment by bart-degreed** [comment]
Unfortunately, you haven't mentioned which database provider you're using (it's in the issue template for a reason). Because that's where the filtering happens, and casing support varies per database type. A simple google for "case insensitive contains filter ef core" yields https://stackoverflow.com/questions/43277868/entity-framework-core-contains-is-case-sensitive-or-case-insensitive, which basically answers your question.

For example, in SQL Server you can set the collation at various levels, such as [at the database level](https://stackoverflow.com/questions/3296428/changing-sql-server-collation-to-case-insensitive-from-case-sensitive) or [at the column level](https://sqlskull.com/2020/10/02/sql-change-column-collation-to-case-sensitive/).

**Comment by MehdiR-S** [comment]
Thanks for your answer @bart-degreed 
Sorry for this, I'm using Postgresql
I know how EF Core works, and how can I do a case insensitive filter with EF Core. But I don't see where can I implement this into JsonApi, I'm doing a "contains()" filter, but that's not case insensitive.

**Comment by bart-degreed** [comment]
If you want an efficient way without compromising query performance, you should change the collation in your database. See https://docs.microsoft.com/en-us/ef/core/miscellaneous/collations-and-case-sensitivity#explicit-collations-and-indexes.

**Comment by MehdiR-S** [comment]
Thank you for your answer.
I used citext to fix my problem.
