### ISSUE TITLE
Question: Would it be possible to apply your `filter` / queryProcessing logic to standard `IEnumerable` / `IQueryable`

### ISSUE THREAD

**Issue by sandreas** [json-api-dotnet/JsonApiDotNetCore#1164]
#### SUMMARY
I really like your approach to [`filter`](https://www.jsonapi.net/usage/reading/filtering.html) / `order` / `paginate` data by a URI query string. Especially the `filter` aggregation with `and`, `or` and `()` is nice and very flexible.

I'm currently developing a small command line audio tagger and asked myself, if it would be possible to apply [YOUR query processing](https://www.jsonapi.net/internals/queries.html) to a generic `IEnumerable` or `IQueryable`?

I would love to see a library providing this part of your work for a more generic purpose...

Basically what I'm asking for is something like this:

```bash
# my command line tool recursiveley iterates over files in a directory and should be able to filter them
tone dump --sort="size" --page=1 --filter=equals(Artist,'AC/DC') /home/sandreas/music
```

```c#
// any class 
class MediaFile {
    public long FileSize;
    public string Artist;
    public IEnumerable<Picture> Covers;
    //... 
}

// a generic enumberable
IEnumerable<MediaFile> mediaFiles = FileWalker.FindMediaFiles();

// your query processing logic applied to this generic IQueryable?!
var queryProcessor = new QueryProcessor(options.Sort, options.Page, options.Filter);
var filteredMediaFiles = queryProcessor.Apply(mediaFiles);

foreach(var mediaFile in filteredMediaFiles) {
    Console.WriteLine(mediaFile.Artist);
}
```

What do you think? Would that be possible / worth the effort?

**Comment by bkoelman** [comment]
That's an interesting idea. My time is limited at the moment, but I intend to experiment with that a bit and get back to you soon.

**Comment by bkoelman** [comment]
I've done some experiments and concluded that extracting the querying logic from JADNC is not feasible at this time. This is due to dependencies on the resource graph, EF Core, HttpContext, and various others. However the good news is: you can already reuse JADNC today for what you're trying to accomplish. Two approaches:

1. Use a light-weight database (such as Sqlite) and split your command-line tool into two modes: one to scan the filesystem and build/refresh the database, the other to query it. This enables lightning-fast queries over multiple resource types. For example: give me all tracks from a specific artist, give me all tracks of this genre, etc. #1144 shows how to accomplish that. This is the easiest solution.
2. Use the approach at #1165, which does not require a database. While scanning the file system, you'd build an in-memory object model of resources and their relationships.

In either case, based on command-line switches you need to construct a query string (matching what JADNC accepts when running as an ASP.NET Web API).

**Comment by sandreas** [comment]
> I've done some experiments and concluded that extracting the querying logic from JADNC is not feasible at this time. 

What a pity, but thank you for digging in.

> 1. Use a light-weight database (such as Sqlite) and split your command-line tool into two modes: 

Well, that may be an option, but I tend to use `KISS` - that feels a bit complicated...

> 2. Use the approach at https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1165, which does not require a database.

Awesome example, thank you for putting so much time into this. I already learned many things besides the query filtering :-) Maybe I'll use this or extract parts of the query processor to fit my needs. I also thought about creating a *Mini-Lisp* since the syntax you use is a bit similar to `(and (eq a b) (gt c d))` or `(and,(eq,a,b),(gt,c,d))`.

I really appreciate your work.

**Comment by bkoelman** [comment]
Glad to help. I wish you good luck with your project.
