### ISSUE TITLE
Need to get only limited number of properties if i pass include keyword in the query string

### ISSUE THREAD

**Issue by bhavik-mittal** [json-api-dotnet/JsonApiDotNetCore#1358]
I have a below models
```
[Resource]
public class Teacher: Identifiable<int>
{
	[HasOne]
	public Subject SubjectDetails { get; set; }
	[Attr]
	public string Qualification { get; set; }
        [Attr]
        public string Name { get; set; }
}
[Resource]
public class Subject: Identifiable<int>
{
	[Attr]
	public string Name {get;set;}
	[Attr]
	public int Credits {get;set;}
	[Attr]
	public int TotalWeightage {get;set;}
}

http://localhost:14141/api/teacher
if i use above endpoint i get the below sample response 
{
  "links": {
    "self": "/api/teacher"
  },
  "data": {
    "type": "teacher",
    "id": "1",
    "attributes": {
      "name": "Mary Shelley",
      "Qualification" : "Bachelors"
    },
    "relationships": {
      "subject": {
        "links": {
          "self": "/api/teacher/1/relationships/subject",
        }
      }
    },
    "links": {
      "self": "/api/teacher"
    }
  }
}
And If i pass include parameter i will get id,Name,Credits,TotalWeightage all in the response in included array
http://localhost:14141/api/teacher?include = subject

{
  "links": {
    "self": "/api/teacher"
  },
  "data": [
  {
    "type": "teacher",
    "id": "1",
    "attributes": {
      "name": "Mary Shelley"
    },
    "relationships": {
      "subject": {
        "links": {
          "self": "/api/teacher/1/relationships/subject",
        },
        "data": {
			"type": "subject",
			"id": "53026"		
		}
      }
    },
    "links": {
      "self": "/api/teacher"
    }
  },
      "included": [
        {
            "type": "subject",
            "id": "53026",
            "attributes": {
                "Name": "Englist",
                "Credits": 2,
                "TotalWeightage": 10,
            },
            "links": {
                "self": "/api/subject/53026"
            }
        }
    ],
  ]
}
```
Now in the above response 'data' property is added in each relationship object and 'included' array is added but 
Is there any way to just add the 'data' field in the object by default which contains id as i only need relationship id only in some cases  instead of whole included array?
If i pass the 
http://localhost:14141/api/teacher?include = subject&fields[subject]=id
this will work i know but is there any way that id should be by default added in the relationship object without the need to pass the 'include' and 'fields' in the queryparams.

The above question arises as the above example stated is very basic which has only one HasOne relationship but in my practical project there is a resource which has 5 HasOne relationships and i just want id of each relationship in the response so now i have to pass the 'fields' queryparam 5 times in querystring for each HasOne relationship to get only the id.

```

**Comment by bkoelman** [comment]
Hi @bhavik-mittal, thanks for asking.

This is not available out of the box by design, because it relies on server implementation details. It would _only_ be possible when Entity Framework Core is used, it involves a to-one relationship, and the foreign key is defined at the side of the resource you're requesting.

However, there are two ways to accomplish what you're asking for:
1. Clear the `include` array before the response is sent. Create your own `IResponseModelAdapter` implementation that delegates to the built-in `ResponseModelAdapter` and register it in the IoC container. Your custom implementation would call the built-in `Convert` method, set `.Included` on the returned document to `null` or an empty array, then return it. This still requires the client to send the `include` query string parameter, but now you can compact the returned JSON response based on any custom logic you provide. Beware though, that you're violating the JSON:API specification, specifically:
    > In a compound document, all included resources MUST be represented as an array of [resource objects](https://jsonapi.org/format/#document-resource-objects) in a top-level included member.

    and:

    > Every included resource object MUST be identified via a chain of relationships originating in a document’s primary data. This means that compound documents require “full linkage” and that no resource object can be included without a direct or indirect relationship to the document’s primary data.

3. Publicly expose the foreign key as a property on Teacher: `[Attr(Capabilities = AttrCapabilities.AllowView)] public int SubjectDetailsId { get; set; }` so it gets fetched and returned as a field within the `attributes` array. Setting the capabilities is optional, it restricts updating the foreign key directly.

**Comment by bhavik-mittal** [comment]
Okay, thanks for the response. Closing the thread for now. will reopen if any further clarifications are required.
