### ISSUE TITLE
Remove Status Field from Error's Response

### ISSUE THREAD

**Issue by abhinavchauhan12** [json-api-dotnet/JsonApiDotNetCore#1449]
I am getting a error response as below :-
```
{
  "errors": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "code": "124",
      "status": "400",
      "title": "Error occurred",
      "detail": "Validation failed"
    }
  ]
}
```
I am using JsonApiException(ErrorObject).
Since , I am setting `status`(Which is mandatory parameter because of ErrorObject and JsonApiException) and `code`(for my own use) both , Is there any way such that response does not include this status field.

**Comment by bkoelman** [comment]
No, there is not. The JSON:API spec states:
> status: the HTTP status code applicable to this problem, expressed as a string value. This SHOULD be provided.

Beware the `error.status` field is needed to determine the HTTP response status. For example, a response body that contains two errors, being 404 and 403, the spec dictates that the server must return 400 as the response status code.

Why would you want to remove this from the response? Clients generally depend on the status codes used, as described by the spec. It enables client libraries in various languages to understand what's going on, because the meaning of these codes is well-defined. For example, it may drive auto-retry behavior.
