### ISSUE TITLE
Weird casing for IfNoneMatch argument in generated NSwag client

### ISSUE THREAD

**Issue by verdie-g** [json-api-dotnet/JsonApiDotNetCore#1467]
NSwag generates the argument as `if_none_match` when `ifNoneMatch` would be expected.

**Comment by bkoelman** [comment]
Looks like this was created in the wrong repo.

**Comment by verdie-g** [comment]
Oh I misread your comment https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1459#issuecomment-1949582165. Do you think a custom argument name generator should be provided in JADNC?

**Comment by bkoelman** [comment]
The way I understand it (correct me if I'm wrong), adding `/ParameterNameGenerator:` in `<Options>` has no effect because the switch does not exist in NSwag. So the ask to NSwag would be to add a new switch to adhere to the C# naming conventions. Internally they would implement another `IParameterNameGenerator` for that, which becomes active when the new switch is used. 

Another way could be to request them to add `/ParameterNameGenerator:`, but that becomes problematic when the implementation lives in another assembly. I find it more realistic that users want to comply with language conventions, than to make this fully customizable.

As far as I'm aware, there's nothing we can do within JADNC other than provide our own executable to generate the client code. Like I said, that goes a bit too far.
