### ISSUE TITLE
Small peculiarities

### ISSUE THREAD

**Issue by shuebner** [json-api-dotnet/JsonApiDotNetCore#212]
**Disclaimer**: I kind of feel bad for opening so many issues. I don't want to be annoying. My sole intention is to help improve this library because the "better" (whatever that means) this library is, the more it will help me with my project. I looked at other JSON API libraries and yours was by far the one appealing to me the most. Thus I am really getting into your library (great job btw!) and notice things of which I don't know if they are intentional, oversights or don't really matter.

# IEntityRepository.UpdateAsync
- is the `entity` parameter really necessary? All the attributes to be updated are in the IJsonApiContext anyway and DefaultEntityRepository does not use the parameter. Is there a use case for other IEntityRepository implementations that use this? Same question up the call chain for `IEntityResourceService.UpdateAsync` and maybe eventually `BaseJsonApiController.PathAsync`. Although I can imagine that having the entity in the controller might be useful.

# ContextGraph
- `Entities` and `UsesDbContext` are only set on initialization and could be set in a constructor instead of having public properties; only `bool UsesDbContext {get;}` is needed; this would convey the immutability of the two members and not expose more than is necessary

# EntityResourceService
- `ApplyPageQueryAsync` declares unused local variable `query`; the declaration seems not to have any side effects either

# IQueryableExtensions
- Last two comments in `IQueryableExtensions.GetFilterExpressionLambda` are wrong (copy-paste)
- `System.Reflection` is declared but not used; this doesn't really matter but maybe gives the wrong impression of what the extensions do

**Comment by jaredcnance** [comment]
No worries! Your issues are detailed and I appreciate the effort you're putting in. No complaints from me!

- IEntityRepository.UpdateAsync

This is an area where I think we can definitely improve upon. We also currently do a fetch prior to performing an update, which I don't think should be necessary (although it's not that simple b/c there are some scenarios we need to support).  One issue with the current implementation is the requirement to use nullable types to determine whether or not the attribute/relationship was actually included in the request. This creates a problem when we want to support relationship deletion since we cannot determine whether or not the relationship was included or set to null. This topic probably deserves its own issue for further discussion.

The remaining items all sound reasonable and my initial reaction is that these are all reasonable suggestions. I'll need more time to review them, but I don't see why we couldn't include them in the next release.

**Comment by shuebner** [comment]
I found something else:
`EntityResourceService.ApplyPageQueryAsync` does not realize the query if there is no paging.
The signature implies it does, though.

So, shouldn't it be `return await entities.ToListAsync()` (as long as we are EF-dependent here)?

**Comment by shuebner** [comment]
And another thing:
I don't see how in `EntityResourceService.GetAsync` the statement

```csharp
_jsonApiContext.QuerySet?.IncludedRelationships != null
```
could ever be false, since `QuerySet.IncludedRelationships` is initialized as empty list and only set with `QueryParser.ParseIncludedRelationships`, which always returns a list.
As a result, the `else` path is never taken.

I think the statement should rather be

```csharp
!_jsonApiContext.QuerySet?.IncludedRelationships.Any()
```

**Comment by jaredcnance** [comment]
@shuebner regarding `ApplyPageQueryAsync`, I'd like to address that in the PR for #211 since it touches on query execution. 

Regarding the last point, I'm not sure I follow. This is the current state on master:
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/12eafc8f32d7350408a1ceccf4443ed2bcc00b44/src/JsonApiDotNetCore/Services/EntityResourceService.cs#L50

This already requires the list to be non-empty.

**Comment by shuebner** [comment]
Ok, I'll include the change to `ApplyPageQueryAsync` in my PR for #211.
I have it locally already anyway.
