### ISSUE TITLE
Namespace not reflected in Links

### ISSUE THREAD

**Issue by accoleon** [json-api-dotnet/JsonApiDotNetCore#305]
NuGet package version 2.3.0
ASP.NET Core 2.1

To reproduce:
1. In ConfigureServices, set opt.Namespace to ="api/v1"
2. Call api from postman

Results:
![image](https://user-images.githubusercontent.com/115630/41440933-5146b000-6fe5-11e8-8720-f4b92d8b400f.png)

**Comment by accoleon** [comment]
Closed because this only occurs in ASP.NET Core 2.1 SPA templates. The use of UseSpa/UseSpaStaticFiles messes up the link generation. Since it isn't recommended to have both the API and frontend in the same project, this really isn't a bug in this project.

**Comment by XaserAcheron** [comment]
I'm running into this as well, and I'm not using any of the SPA stuff. I don't think I'm doing anything unusual, really.

**Comment by XaserAcheron** [comment]
Huh, weird -- I realized I was doing the same thing that caused [url=https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/57]this issue[/url] (using singular instead of plural names for the DbSets on my DbContext), and after correcting that, the namespace shows up now. May have been a red herring, then.
