### ISSUE TITLE
Determine Future of RelationshipsToUpdate

### ISSUE THREAD

**Issue by Fireblade954** [json-api-dotnet/JsonApiDotNetCore#331]
_jsonApiContext.RelationshipsToUpdate is not set for HasMany relations on PATCH requests?

in function SetHasOneRelationship _jsonApiContext.RelationshipsToUpdate is set.
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/271693a27c846b32ddb3691e781fbff3e1d70a8c/src/JsonApiDotNetCore/Serialization/JsonApiDeSerializer.cs#L232

in function SetHasManyRelationship _jsonApiContext.RelationshipsToUpdate is NOT set.

is this by design? or forgotten?

**Comment by jaredcnance** [comment]
The `RelationshipsToUpdate` dictionary is used to set the FK properties on `HasOne` relationships:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/271693a27c846b32ddb3691e781fbff3e1d70a8c/src/JsonApiDotNetCore/Serialization/JsonApiDeSerializer.cs#L229-L232

In the case of `HasMany`, there are no FK properties to update since the `HasMany` attribute should exist on the independent side of the relationship. Instead, we track pointers to the relationship through `HasManyRelationshipPointers`/`HasOneRelationshipPointers`

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/271693a27c846b32ddb3691e781fbff3e1d70a8c/src/JsonApiDotNetCore/Serialization/JsonApiDeSerializer.cs#L281

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/448114793a72e134f7720f436e34855df3532d32/src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs#L94-L114

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/448114793a72e134f7720f436e34855df3532d32/src/JsonApiDotNetCore/Services/IJsonApiContext.cs#L54-L107

Perhaps the oversight is not deprecating the `RelationshipsToUpdate` dictionary. It looks like we should be able to use `HasOneRelationshipPointers` only. 

This change was made in v2.3.2 via #314. Was this a breaking change for you?

**Comment by Fireblade954** [comment]
Not necessarily a breaking change just did the assumption RelationshipsToUpdate contained all relations send in a PATCH request. We are not directly connected to the dbContext so i need to process the relations send in the patch request manually.

Ill use HasOneRelationshipPointers  and HasManyRelationshipPointers to update my entities.

**Comment by jaredcnance** [comment]
@Fireblade954 I understand the confusion. I'm going to leave this issue open so we can track plans on improving this experience. I've also created https://github.com/json-api-dotnet/json-api-dotnet.github.io/issues/6 to track documentation improvements.

**Comment by maurei** [comment]
Outdated
