### ISSUE TITLE
Identifiable<string> causes exceptions in Post

### ISSUE THREAD

**Issue by Nihimon** [json-api-dotnet/JsonApiDotNetCore#382]
## Description

I created a prototype Api using a simple model class inheriting Identifiable<int> and a custom IResourceService (to avoid using EF) and tested the Post and primary Get methods.  Everything worked great.

I then tried to change the model class to inherit Identifiable<string> (to match our production system).  The Gets work fine, but the Post threw exceptions.  First, it threw a NullReferenceException in GetStringId before the Controller Action was called.  I set the Id in the constructor and then it returned 403 Forbidden.

I also tested using Identifiable<Guid> which worked as expected.

I created a demo solution (basic Asp.Net Core 2.1 Api only adding JsonApiDotNetCore) to demonstrate the problem.  I made changes in Startup.cs, and added three Controllers (and related classes).

You can find the demo solution at [JsonApiDotNetCore-Bug-Reproduction](https://github.com/Nihimon/JsonApiDotNetCore-Bug-Reproduction).

Note that my-ints and my-guids work as expected, while my-strings fails with the exceptions above.

## Environment

Visual Studio 2017 Professional 15.8.1

- JsonApiDotNetCore Version: 2.5.1
- Other Relevant Package Versions: Microsoft.NETCore.App 2.1.0, Microsoft.AspNetCore.App 2.1.1

**Comment by jaredcnance** [comment]
Thanks for reporting this and the reproduction. The null ref is thrown here:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/23329ab1b6d20494e29e7943fec1acea8bd7ca6a/src/JsonApiDotNetCore/Models/Identifiable.cs#L41

I'm unsure why this wasn't caught by our tests right now. As a quick fix, you can add this line to your model and things should work for you.

```c#
protected override string GetStringId(object value) => value?.ToString();
```

> I set the Id in the constructor and then it returned 403 Forbidden

By setting the `Id` in the constructor, the controller believes the id was set by the client ans since `AllowClientGeneratedIds` is disabled by default, that is why you received a 403.

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/f05b46646f79f131c09f2c59de8cce20a93bf072/src/JsonApiDotNetCore/Controllers/BaseJsonApiController.cs#L155-L156

**Comment by Nihimon** [comment]
That makes sense.  Thanks for the quick reply and the workaround.
