### ISSUE TITLE
Small mistake in documentation

### ISSUE THREAD

**Issue by maurei** [json-api-dotnet/JsonApiDotNetCore#407]
In https://json-api-dotnet.github.io/#/layer-overview, the code example mentions

```c#
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    // custom service
    services.AddScoped<IEntityRepository<Person>, CustomPersonService>();

    // custom repository
    services.AddScoped<IEntityRepository<TodoItem>, AuthorizedTodoItemRepository>();

    // ...
}
```

The first `IEntityRepository` should be `IResourceService`
...

**Comment by jaredcnance** [comment]
Thanks! I'm in the process of updating the docs, so I'll be sure to fix this.

**Comment by maurei** [comment]
Just wondering, are there more complete API docs coming up?

**Comment by jaredcnance** [comment]
> API docs

Are you referring to generated API documentation or usage documentation like we already have? I'm currently working on improving the usage documentation we already have. With respect to generated API documentation, it's a bit tricky b/c there haven't been a lot of great tools for OSS project (or any project really) in the .Net ecosystem. I have high hopes for docfx, but the tooling hasn't been great for xplat (it requires mono). The next step for getting the generated documentation out there is to figure out how to deploy it as a static site from Appveyor as part of the CI build.

**Comment by maurei** [comment]
Yep API documentation is what I meant. I don't have any experience with it either for .net core projects though...

**Comment by jaredcnance** [comment]
I started messing around with docfx again last night and they’ve made a lot of great improvements since the last time I used it (and they have a distribution for OSX). My plan is to figure out deployment and then focus my efforts on unifying the usage and API documentation. Most of the public APIs should already be  documented (in source code), but while I’m working on this I’ll continue to work on documenting the rest of the public API surface.
