### ISSUE TITLE
Validate model state not working?

### ISSUE THREAD

**Issue by wayne-o** [json-api-dotnet/JsonApiDotNetCore#411]
## Description
I am trying to use https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/316 by adding this to my Models:

```
 [Required(AllowEmptyStrings=false)] 
[StringLength(30, MinimumLength = 5, ErrorMessage = "Invalid - Name needs to be at least 5 characters long")]
```

And this in my startup:

```
 services.AddMvcCore()
                .AddDataAnnotations()
```

But it seems to completely ignore it  -is there anything else I need to do to get this to work?

...

## Environment

- JsonApiDotNetCore Version:  latest stable (v2.5.2)
- Other Relevant Package Versions:

**Comment by wayne-o** [comment]
I'm trying upgrading to the latest beta - I'll come back with the result

**Comment by wayne-o** [comment]
No change :/ even latest does not seem to apply

**Comment by jaredcnance** [comment]
Have you enabled `ValidateModelState` ? This was put behind a feature flag since it wasn't initially checked and would have been a breaking change.

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/491a6cbed1b68a6fcc9ce69ca8b00d3b20b586c7/src/JsonApiDotNetCore/Configuration/JsonApiOptions.cs#L128-L136

**Comment by wayne-o** [comment]
Ahhhh ok - trying now :)

**Comment by wayne-o** [comment]
Works perfectly :)
