### ISSUE TITLE
More helpful exception if resource has not been registered to contextgraph

### ISSUE THREAD

**Issue by wisepotato** [json-api-dotnet/JsonApiDotNetCore#414]
## Description
So I am currently in the works of implementing a many-to-many relationship in V3.0.0v4, and thank god I have the source code next to it, because in the documentbuilder you need the `typeName`, which is fair, but what if it isnt set? (say I forgot it.) Seeing as you absolutely need it, and a nullpointer exception is anything but helpful shouldn't this include an exception?

If yes, I'll make a pull request, need to first test the waters of this package

## Environment

- JsonApiDotNetCore Version: 3.0.0v4
- Other Relevant Package Versions:

**Comment by wisepotato** [comment]
Cool, I don't contribute much but I'll get a test going as well for this. hold tight 👍

**Comment by wisepotato** [comment]
which branch should i contribute to though? I'm currently working on a fork of V3.0.0.v4

**Comment by jaredcnance** [comment]
In general, you should always base your work off `master` and then PR back to master. In some cases when we're working on a beta release, we may choose to port back to the latest stable (loosely documented [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/CONTRIBUTING.MD#backporting-features-to-prior-releases)).

**Comment by bart-degreed** [comment]
Since this issue was reported, a lot of code has changed. However I think this boils down to: `IResourceContextProvider.GetResourceContext()` (evolved from `ContextGraph.GetContextEntity()`) should throw instead of return `null` when not found. And there should be a way to check without throwing but possibly returning `null`. With these two building blocks in place, we'll need to review all usages and update accordingly to ensure proper errors are produced.

This is tracked as part of #1029, so I'm closing this.
