### ISSUE TITLE
Escaped Commas cannot be used in a filter string

### ISSUE THREAD

**Issue by mary-gao** [json-api-dotnet/JsonApiDotNetCore#444]
## Description
It's not possible right now to search for items using a comma in the filter string. So, when I GET

> /entities?filter[name]=like:%2C

I don't get the entries that I expect (all the entities with a name that contains a comma).

It looks like this is because we [split the filter string on the comma](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/3e253812ae0ff4732aaadd134dd269bc9c96895b/src/JsonApiDotNetCore/Services/QueryParser.cs#L97) after it has already been decoded, so we do not distinguish between "?filter[name]=a%2Cc" and "?filter[name]=a,c".

## Environment
- JsonApiDotNetCore Version: 2.4.0

**Comment by jaredcnance** [comment]
🤔 I'm not sure that we should distinguish between encoded and non encoded commas (or even if we can—if i remember correctly, it's already decoded when we get it). This behavior comes from the JSON:API recommendations on filtering: https://jsonapi.org/recommendations/#filtering/

But, maybe we should add a flag to opt out of comma separated values. Would that work for your needs? And if so, would you use it app-wide or on a per resource basis?

**Comment by mary-gao** [comment]
I was hoping to use comma separated value parsing as well, actually. I noticed that the url was decoded already by the time the query parsing happened, but I don't know why that is. Couldn't we get the unescaped string directly from the request in the controller, and then split the query parameters, and then decode the query parameters?

**Comment by ScottEDubya** [comment]
I don't think the jsonapi spec specifically says anything about what you should/shouldn't be able to filter on. if i wanted to filter on multiple things with commas in their names, my url should look like the following:
`http://domain.com/entities?filter[name]=foo%2C%20bar,boo%2C%20far`
so we could search for two names "foo, bar" and "boo, far". there's a distinguishable difference in the literal URL between the commas for value separation and the commas which we're looking for in our filter.

i think this is related/under the hood nearly the same issue as the one i opened a bit ago: #408
the way the library is handling the url (or possibly allowing .net core to do the url parsing in its default way maybe?) is limiting our ability to effectively filter our data sets

**Comment by jaredcnance** [comment]
I think that's an accurate assessment. What we'll need to figure out is how to the raw url encoded values since it looks like AspNetCore already decodes them when deserializing to `string`. Right now we're just passing in the [`HttpContext.Request.Query`](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/8570b216c7ede3a7b5f9fc7a4912404a14926df5/src/JsonApiDotNetCore/Services/JsonApiContext.cs#L73)

**Comment by ScottEDubya** [comment]
Yeah, @mary-gao seems to have found that the controllers do have access to the literal query string, but as far as it being the right solution to write jsonapi's own parser, i'm not sure about that one. feels like something someone in the past would have run into and there might already be an elegant solution out there!

**Comment by jaredcnance** [comment]
In order to implement this, we will need to use `HttpContext.Request.QueryString` instead of `HttpContext.Request.Query`. The difference here is that `QueryString` contains the raw string value prior to parsing. But, that means we'll need to split the query string on `&` and `=` ourselves. This isn't great because that means AspNetCore will be doing unnecessary work and allocations when parsing and constructing the `QueryCollection`. So, then for every request the path is stored in at least 3 different locations in memory (but probably 4 since it's probably accessible through the Location header as well).

![image](https://user-images.githubusercontent.com/13851721/48423920-6b485780-e716-11e8-9748-43b364007b3b.png)

It would be a lot better if we could hijack the parsing work. I did some quick looking but haven't found where the `QueryCollection` actually gets built in the AspNetCore pipeline.

**Comment by jaredcnance** [comment]
Digging a little further this is where it happens:

- The `Query` object is stored in the `QueryFeature`
https://github.com/aspnet/HttpAbstractions/blob/1d3521113ad69a9903d1590c77d67da04c5f5dfd/src/Microsoft.AspNetCore.Http/Internal/DefaultHttpRequest.cs#L116

- Which is loaded from a cache
https://github.com/aspnet/HttpAbstractions/blob/1d3521113ad69a9903d1590c77d67da04c5f5dfd/src/Microsoft.AspNetCore.Http/Internal/DefaultHttpRequest.cs#L48-L49

- or a new one is created
https://github.com/aspnet/HttpAbstractions/blob/1d3521113ad69a9903d1590c77d67da04c5f5dfd/src/Microsoft.AspNetCore.Http/Internal/DefaultHttpRequest.cs#L18

- when the `Query` is requested it calls into `QueryHelpers.ParseNullableQuery`
https://github.com/aspnet/HttpAbstractions/blob/1d3521113ad69a9903d1590c77d67da04c5f5dfd/src/Microsoft.AspNetCore.Http/Features/QueryFeature.cs#L61

- which decodes the characters
https://github.com/aspnet/HttpAbstractions/blob/1d3521113ad69a9903d1590c77d67da04c5f5dfd/src/Microsoft.AspNetCore.WebUtilities/QueryHelpers.cs#L166

So, based on that we'd need a way to provide a custom `HttpRequest` implementation that inherits from `DefaultHttpRequest` and just changes the query parsing behavior. If that's not possible, then we'll need to parse the `QueryString` ourselves.

As a side note this would be a breaking change since I suspect some clients are already encoding `,` as `%2C` and using it as an `&key=value2` replacement.

**Comment by roblankey** [comment]
Alternatively, what about just using a CSV-type parser and surrounding filter values containing commas with quotes. CsvHelper and TinyCsvParser are the two that jumped out pretty quickly when searching.

**Comment by jaredcnance** [comment]
I don't think we need to bring a dependency in for this. Parsing is not difficult. I just didn't want to do extra work on each request if we didn't need to. I think to avoid a breaking change and unexpected behavior for existing users we can:

- Introduce an `IQueryParamParser`:

```c#
public interface IQueryParamParser {
  QueryCollection GetParsedQueryParams();
}
```

- Add a default implementation:

```c#
public class DefaultQueryParamParser : IQueryParamParser {
  private readonly HttpContext _httpContext
  public DefaultQueryParamParser(IHttpContextAccessor httpContextAccessor) {
     _httpContext = httpContextAccessor.HttpContext;
  }
  public QueryCollection GetParsedQueryParams() => _httpContext.Request.Query;
}
```

- Add optional encoded comma implementation

```c#
// better name desired...
public class EncodedValueQueryParamParser : IQueryParamParser { /* TBD */ }
```

- Provide either a strategy enum on `JsonApiOptions` or just require the user to inject the service.

```c#
services.AddJsonApi(options => {
  options.QueryParsingStrategy = QueryParsingStrategy.KeepEncodedValues;
});

services.AddScoped<EncodedValueQueryParamParser, DefaultQueryParamParser>();
```
