### ISSUE TITLE
useage of FilterQuery and obsolete

### ISSUE THREAD

**Issue by wisepotato** [json-api-dotnet/JsonApiDotNetCore#469]
## Description

When internally using `FilterQuery`, I get the message that `FilterQuery.Key` is obsolete. Key has been replaced by 'Attribute`  Members should be located by their public name, not by coercing the provided value to the internal name.

What exactly is the takeaway here?You shouldnt use FilterQuery? Or it should transition to using Attribute?

**Comment by jaredcnance** [comment]
No, `FilterQuery` is not obsolete. Only the property `FilterQuery.Key` which has been replaced by `FilterQuery.Attribute`.

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/f72e8ae2247b39fbf1bf5af446b27e9420cf01f4/src/JsonApiDotNetCore/Internal/Query/FilterQuery.cs#L28-L29
is replaced by:
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/f72e8ae2247b39fbf1bf5af446b27e9420cf01f4/src/JsonApiDotNetCore/Internal/Query/BaseQuery.cs#L22

The difference here is that `Key` made some assumptions about your code convention, specifically that C# property names should be proper cased and we could reliably map the external attribute to the internal property name (e.g. `"compound-name"` -> `CompoundName`). However, this is not reliable because the internal name may be different from the external name. So, instead, anytime you use queries you should use the expected external name `"compound-name"` (`FilterQuery.Attribute`) rather than the proper cased internal property (`FilterQuery.Key`).

**Comment by wisepotato** [comment]
why is the expected external name `compond-name` anyway? isnt the normal expectation within jsonapi to be `compoundName`?

**Comment by wisepotato** [comment]
thanks for your explanation btw

**Comment by jaredcnance** [comment]
@wisepotato camelCase did not become the recommended convention until a [few months ago](https://github.com/json-api/json-api/pull/1297) and kebab-case was the previously recommendation. But it really doesn't matter since you can use whichever convention you prefer.
