### ISSUE TITLE
Filter included relations

### ISSUE THREAD

**Issue by medokin** [json-api-dotnet/JsonApiDotNetCore#474]
## Description
Let's assume I have two entities.

A `Person` that has many `Transaction`. I've implemented a `TransactionService` to hide some transactions from the user.

Works great when querying `Transaction`, but when I query a `Person` with `include=transactions`, it includes the hidden transactions.

Am I missing something, or do I need to reimplement the filter in every relation of `Transaction`?

Thanks for this great piece of software!
## Environment

- JsonApiDotNetCore Version: 3.0.0
- Other Relevant Package Versions: Core 2.2

**Comment by jaredcnance** [comment]
@medokin there are two issues here. The first is due to a design flaw in JADNC that we still need to resolve. Currently, when you include resources, this is done from the target resource service. 

- `/persons` → `PersonService`
- `/persons?include=transactions` → `PersonService`
- `/transactions?include=person` → `TransactionService`

Any logic you've defined in the `TransactionService` won't be invoked unless `transaction` is the target resource. 

One option you have is to run your same filtering logic in the `PersonService` if the included relationship is `transactions`. So, instead of:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/a1241eeb38c43d82760bb134b09d439ecdce3476/src/JsonApiDotNetCore/Services/EntityResourceService.cs#L231-L238

You might try:

```
foreach (var r in relationships) {
  entities = _entities.Include(entities, r);
  if(r?.Equals("transactions")) {
    // add filtering logic here
  }
}
```

The second issue (depending on what you're trying to do) is described here: [aspnet/EntityFrameworkCore#1833 Support filtered Include](https://github.com/aspnet/EntityFrameworkCore/issues/1833). One alternative is to load transactions into memory and the perform the filtering, but this will not scale well.

**Comment by medokin** [comment]
@jaredcnance Thanks for the thorough explanation. I agree that the lack from EF for include filters can result in scaling issues. 

As a workaround, my solution now prevents the inclusion of transactions from related entities like this.

```c#
        protected override IQueryable<Person> IncludeRelationships(IQueryable<Person> entities, List<string> relationships)
        {
            relationships.Remove("transactions");

            return base.IncludeRelationships(entities, relationships);
        }
```

**Comment by wisepotato** [comment]
I mean doesnt this call for a more generic Access Control system? Something thats tied to the model and therefore gets implemented in every layer? This can stand on its own I guess. Just spitballin' here. Might look into this.

**Comment by wisepotato** [comment]
Running the same logic /repeating yourself is of course not the proper way

**Comment by maurei** [comment]
This has been solved with the introduction of resource hooks in v4. The proper way would now be to implement the `OnReturn` or `AfterRead` for the `Transaction` resource.

```c#
    public class TransactionResource : ResourceDefinition<Transaction>
    {
        public TransactionResource(IResourceGraph graph) : base(graph) { }

        public override IEnumerable<Transaction> OnReturn(HashSet<Transaction> entities, ResourcePipeline pipeline)
        {
            return entities.Where(t => !t.ShouldHide);
        }
    }
```

This hook will be fired in both cases:
- /persons?include=transactions 
- /transactions 


For more information, [see the docs for resource hooks](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/docs/usage/resources/hooks.md). Docs are a little out of date, see https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/552 about that
