### ISSUE TITLE
Modifiable related links protocol

### ISSUE THREAD

**Issue by joshhubers** [json-api-dotnet/JsonApiDotNetCore#521]
## Description
A bit of an issue I've ran into is that when related links are created for related models it uses the protocol from the default configuration. This is problematic as I'm running an application behind a load balancer/proxy with SSL termination. So while the server itself is only http, the related links need to be https for consuming applications to fetch related resources over https.

I know links can be disabled, but that's not exactly a great solution for when links are needed for certain consumers and frameworks.

I'd be happy to look into this if I get time.
...

## Environment

- JsonApiDotNetCore Version: 3.1.0
- Other Relevant Package Versions:

**Comment by maurei** [comment]
Sounds like there is no way to register your own `LinkBuilder` and provide JsonApiDotNetCore with a custom linkbuilding? I feel this would be the way to fix your problem.

**Comment by maurei** [comment]
@joshhubers 

The way I propose to solve this is the following. Right now, `LinkBuilder` is not registered with DI and instantiated internally by `DocumentBuilder` and `JsonApiContext`. I propose to change so that `LinkBuilder` implements `ILinkBuilder`:

```
public interface ILinkBuilder
{
    string GetBasePath(HttpContext context, string entityName);
    string GetPageLink(int pageOffset, int pageSize);
    string GetRelatedRelationLink(string parent, string parentId, string child);
    string GetSelfRelationLink(string parent, string parentId, string child);
}

public class LinkBuilder : ILinkBuilder
{
    ...
}
```
And then register the current `LinkBuilder` class as the default implementation. You can then register a manual implementation that suits your needs.

Let me know if this works for you. I think I will be able to implement this in the follow week or the one after. Or if you want to give it a try feel free.

**Comment by joshhubers** [comment]
That works for me!

Thanks for the thoughts! I can implement this myself in the same time period, this week or the next and open a PR.

**Comment by ngboardway** [comment]
@maurei Considering the LinkBuilder constructor currently takes the JsonApiContext as a parameter (and the link building is coupled to the context rather heavily), can you think of any way to use DI to inject the correct implementation of ILinkBuilder that doesn't require refactoring the construction/ use of the LinkBuilder to remove the JsonApiContext from the builder (since it would result in a circular dependency)?

**Comment by ngboardway** [comment]
It looks like a lot of this work is being started in #504 (I noticed the introduction of the ILinkBuilder interface). Waiting to see how that plays out before duplicating the refactoring that's happening there.

**Comment by maurei** [comment]
It will take at least several weeks more for #506 (which is the PR for #504) to be finished and merged because the scope of the project to decouple the entirety of `IJsonApiContext` is a lot bigger than just refactoring `LinkBuilder` into `ILinkBuilder`. Feel free to start refactoring  `ILinkBuilder`  in a separate PR so we can release that earlier and make it available to you guys.

**Comment by wisepotato** [comment]
Yeah i'll be working on #506 next week, but wont finish probably

**Comment by ngboardway** [comment]
I think we're still going to wait. We have a workaround in place for the time being and like the direction the PR is heading (especially the request manager). We'll check back in a few weeks once you've had a chance to work on it more and see if/ what more still needs to be done.

**Comment by wisepotato** [comment]
I would suggest proposing a PR that introduces an ILinkBuilder for your needs, and I will integrate this into #506 , so that no duplication will be necessary. Or you can wait, up to you :)

**Comment by ngboardway** [comment]
What we need is to be able to override the scheme of the base path. (based on your pr) this has technically been moved out of the LinkBuilder altogether. If the base path is only set in the request middleware, we're thinking that adding an option to the I/JsonApiOptions could be more helpful. Whether that's a boolean that the scheme should always use https, providing a string, etc.

**Comment by maurei** [comment]
My intuition says that says that base path should still be part of LinkBuilder and @wisepotato was planning on putting it back in there but didn't get there yet. I could be wrong though, I haven't thought it through in much detail

**Comment by maurei** [comment]
See #558
