### ISSUE TITLE
Enhancement Request: Read-Only Service interface

### ISSUE THREAD

**Issue by rpatrick00** [json-api-dotnet/JsonApiDotNetCore#535]
## Description
I am trying to use the framework to access read-only data stored in Elasticsearch.  Taking the recommended approach, I started customizing the service layer only to realize there were a dozen or so create, update, and delete interfaces I needed to implement that were irrelevant to my use case.  I think it would be nice if the service layer interface had a read-only interface that I could extend.

**Comment by wisepotato** [comment]
you need to disable a few methods but this is certainly possible, can you give an example of these "dozens" of interfaces? We're open to these suggestions, as a readonly service is a great addition. @maurei  thoughts?

**Comment by wisepotato** [comment]
Althought this isn't too much work to implement. Will investigate.

**Comment by rpatrick00** [comment]
I’m not sure how to “disable” the methods.  Simply throw a not implemented exception?

My object generally has no need for create, update, delete operations on the object or relationships.  Also, we do not support GetAll without filters.

**Comment by wisepotato** [comment]
well a not implemented would server well, or a jsonapiexception would serve nice as you have control voer the status code

**Comment by maurei** [comment]
Hi @rpatrick00, 

If I'm not mistaken, the interfaces you're looking for can be found [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/src/JsonApiDotNetCore/Services/Contract). Looks like you want to use the  `IResourceQueryService<T>`. 

If you need custom service code, you can just use this to build your own implementation and register that one
```c#
// implementation
public class ReadOnlyResourceService<T> : IResourceQueryService<T> { ... }

// registering
services.AddScoped<IResourceService<T>, ReadOnlyResourceService<T>>();
```
If you still want to  use the boilerplate code from `EntityResourceService<T>`: I believe you can simply inherit it and register that
```c#
// implementation
public class ReadOnlyResourceService<T> : EntityResourceService<T> { ... }

// registering
services.AddScoped<IResourceService<T>, ReadOnlyResourceService<T>>();
```
This way you can just ignore the create, update, delete methods because they will not be exposed.


Then there is a `JsonApiQueryController` that [seems to be designed for read-only resources](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/a82a241fec60ec4049635bffc284e9dbe22cfa91/src/JsonApiDotNetCore/Controllers/JsonApiQueryController.cs#L19).  I would have expected a constructor that takes the query service:

```c#
        public JsonApiQueryController(
            IJsonApiContext jsonApiContext,
            IResourceQueryService<T, TId> resourceQueryService)  // <--- is actually IResourceService in the current implementation
        : base(jsonApiContext, resourceService)
        { }
```

But interestingly there is only a constructor that accept  `IResourceService`, which exposes also the create/update/delete operations. I think we should add the constructor above.

For now, you could add the following workaround base controller for your readonly resources

```c#
    public class JsonApiReadOnlyController<T, TId>
            : BaseJsonApiController<T, TId> where T : class, IIdentifiable<TId>
    {
        public JsonApiReadOnlyController(
            IJsonApiContext jsonApiContext,
            IResourceQueryService<T, TId> resourceService)
        : base(jsonApiContext, resourceService)
        { }

        [HttpGet]
        public override async Task<IActionResult> GetAsync() => await base.GetAsync();

        [HttpGet("{id}")]
        public override async Task<IActionResult> GetAsync(TId id) => await base.GetAsync(id);

        [HttpGet("{id}/relationships/{relationshipName}")]
        public override async Task<IActionResult> GetRelationshipsAsync(TId id, string relationshipName)
            => await base.GetRelationshipsAsync(id, relationshipName);

        [HttpGet("{id}/{relationshipName}")]
        public override async Task<IActionResult> GetRelationshipAsync(TId id, string relationshipName)
            => await base.GetRelationshipAsync(id, relationshipName);
    }
```

so that you can have your controllers as follows

```c#
    public class YourResourceController : JsonApiReadOnlyController<YourResource, int>
    {
        public CompaniesController(
            IJsonApiContext jsonApiContext,
            IResourceQueryService<YourResource, int> queryService)
        : base(jsonApiContext, queryService)
        { }
    }
```


Let me know if this solves your problem.

**Comment by rpatrick00** [comment]
@maurei, thanks!  That's a huge help.  I will give it a try.

**Comment by maurei** [comment]
closing as question resolved, created a new issue dedicated to the problem I mentioned in my earlier comment
