### ISSUE TITLE
Support for DB-first scaffolding?

### ISSUE THREAD

**Issue by UpQuark** [json-api-dotnet/JsonApiDotNetCore#540]
## Description

Hi folks,

I'm experimenting with converting a .NET Core backend to use this package so it can play nicer with an Ember frontend's JSON API support. I already have an existing DB that I've been using `dotnet ef dbcontext scaffold` to scaffold models and a DBContext from. I notice the docs at https://json-api-dotnet.github.io/#/step-by-step only mention application-first DB-schema creation using a migration. Is there any currently supported way to scaffold from the DB with the `HasMany` / `HasOne` attributes included, or is only the other way supported? 

Right now I'm using [EntityFrameworkCore.Scaffolding.Handlebars](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars) to customize the scaffolded models, which actually works reasonably well but definitely leads to some pretty hairy logic to decide when to add `HasMany` / `HasOne` attributes.

Thanks!

**Comment by maurei** [comment]
The only thing that DbContext is used for by the JADNC framework is to build the [ResourceGraph](https://json-api-dotnet.github.io/JsonApiDotNetCore/usage/resource-graph.html) (which is a map of all the json:api resources and their relationships that your API serves). JADNC doesn't care how the DbContext got there, so it doesn't matter if you created it through a code-first or database-first approach. 

Note that you can also build the resource graph without using a EF Core DbContext, eg by [manually registering your resource with the resource graph](https://json-api-dotnet.github.io/JsonApiDotNetCore/usage/resource-graph.html#manual-specification), or by [having JADNC reflect on your assembly (auto discovery)](https://json-api-dotnet.github.io/JsonApiDotNetCore/usage/resource-graph.html#auto-discovery). Thus, since the job can be done without relying on DbContext, I hope it makes sense that JADNC doesn't depend on having used a code-first or db-first approach :). Along the same lines of reasoning: I'm not familiar with the Handlebars library, but it shouldn't affect the way JADNC behaves in your application.

With respect to setting up which relationships are exposed in your API (this is also stored in the ResourceGraph): currently the only way to configure this is by using the relationship attributes `[HasMany]`, `[HasOne]` etc inside the class definitions of your models. This means that when calling `services.AddJsonApi<TContext>()` as in the step-by-step example of the docs, it doesn't parse EF Core metadata for the relationships in your models: you'll still need to add the relationship attributes. We are considering to add support for something like this in a future version, as well as supporting a fluent configuration of the resource graph to configure relationships ([similar to EF Core](https://www.learnentityframeworkcore.com/configuration/fluent-api)).
 
About this:
>  but definitely leads to some pretty hairy logic to decide when to add HasMany / HasOne attributes.

Im curious about this: can you show us how exactly this will be tedious in your application?

Let me know if this answered your questions and feel free to ask any more 👍

**Comment by UpQuark** [comment]
Hi @maurei, yes this was totally helpful, thanks for your answer! I'm new to EF Core and JsonApiDotNetCore so forgive any ignorance of basic concepts.

My issue is basically about my personal development style with JsonApiDotNetCore; I'm regularly doing DB updates and re-scaffolding my models from the altered DB. This overwrites any `HasMany()` / `HasOne()` attributes that I've manually added to my models; so my issue is more with my models than the DBContext, which I haven't had to make any manual changes to.

The app I'm working on now is just a side project and I only have 4 major relationships right now, so realistically it isn't a major inconvenience, but I've gone down this rabbit hole of trying to get `HasMany` / `HasOne` to auto-generate from the scaffold, rather than me manually adding the relationships.

I ended up with the slightly strange (but functional) solution I mentioned above that changes the scaffolded models to cooperate with JADNC out of the box. Basically, EntityFrameworkCore.Scaffolding.Handlebars adds scaffolding "templates" (sort of similar to JSX but with uglier syntax, where you can import partial files and reference functions inline with text) that I can edit to change the models generated by the scaffold to be JADNC friendly so I can regularly rebuild them.

So for example it generates a default `Class.hbs` handlebars template that I can then edit to include the JADNC boilerplate:

Default template:
```
{{> imports}}
using JsonApiDotNetCore.Models

namespace {{namespace}}
{
{{#if class-annotation}}
{{{class-annotation}}}
{{/if}}
    public partial class {{class}} : Identifiable
    {
        {{{> constructor}}}
        {{{> properties}}}
    }
}
```

...to which I added:
**`using JsonApiDotNetCore.Models`**
...and:
**`public partial class {{class}} : Identifiable`**
for the boilerplate items. 

Then for the `{{{properties}}}` section which references a template which iterates over all the properties/attributes and relationships/attributes and generates the model code for them, I added a set of helper functions that reads over all the EF-Core attributes and determines whether to add a HasMany or HasMany attribute (the logic I have so far is if there's both ForeignKey and InverseProperty attribute, add HasOne, otherwise if just an InverseProperty attribute, add HasMany). 

I also added a small helper to add "override" to the "Id" property if there is one, which there is on mine, so there isn't an ambiguous reference error from having two conflicting "Id" properties in the hierarchy.

So I end up with a scaffolded model that looks like:

```
namespace MyProject.Models
{
[Table("pricingTier")]
    public partial class PricingTier : Identifiable
    {
        public PricingTier()
        {
            Subscription = new HashSet<Subscription>();
        }

        [Column("id")]
        [Attr]
        public override int Id { get; set; }
        // Properties and such omitted
  
        [HasOne("plan")]
        [ForeignKey("PlanId")]
        [InverseProperty("PricingTier")]
        public virtual Plan Plan { get; set; }
        
        [HasMany("subscription")]
        [InverseProperty("PricingTier")]
        public virtual ICollection<Subscription> Subscription { get; set; }
    }
}
```

It strikes me as a pretty weird / potentially sub-optimal solution but actually does a good job of scaffolding models where relationships default to being exposed, as I want them to be for now.

**Comment by maurei** [comment]
Interesting approach with handlebars! Thanks for that.

It seems you have a good use-case for being able to configure relationships outside the model definitions. We'll weigh that in when we select new features to work on!

Closing as question answered :)
