### ISSUE TITLE
Allow for multiple naming conventions (camelCase vs kebab-case)

### ISSUE THREAD

**Issue by ahmadalli** [json-api-dotnet/JsonApiDotNetCore#555]
## Description

json:api documentation recommends using camelCase instead of kebab case [here](https://jsonapi.org/recommendations/) and is discussed on https://github.com/json-api/json-api/issues/1255.
Is it possible to change naming convention to camelCase or adding configuration for naming convention?

**Comment by wisepotato** [comment]
This seems the way to go, with the option to turn on kebab-case if need be

**Comment by maurei** [comment]
You can define a  newtonsoft `ContractResolver` on `IJsonApiOptions`, see [this example](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/676b654d8f2fde99f1f150abbe52c48496eb1518/src/JsonApiDotNetCore/Configuration/JsonApiOptions.cs#L184).

Let me know if you figure it out

**Comment by ahmadalli** [comment]
I've changed the ContractResolver using `options.SerializerSettings.ContractResolver = new CamelCaseContractResolver();`

and this is my `CamelCaseResolver`:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Humanizer;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace Serialization
{
    public class CamelCaseContractResolver : DefaultContractResolver
    {
        protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
        {
            JsonProperty property = base.CreateProperty(member, memberSerialization);

            property.PropertyName = property.PropertyName.Camelize();

            return property;
        }
    }
}
```

but I'm getting kebab-case result on my api

**Comment by ahmadalli** [comment]
I've added this nameformatter:

```csharp
using System;
using System.Reflection;
using Humanizer;
using JsonApiDotNetCore.Graph;
using JsonApiDotNetCore.Models;

namespace Serialization
{
    public class CamelCaseResourceNameFormatter : IResourceNameFormatter
    {
        public string FormatResourceName(Type resourceType)
        {
            try
            {
                // check the class definition first
                // [Resource("models"] public class Model : Identifiable { /* ... */ }
                if (resourceType.GetCustomAttribute(typeof(ResourceAttribute)) is ResourceAttribute attribute)
                    return attribute.ResourceName;

                return ApplyCasingConvention(resourceType.Name.Pluralize());
            }
            catch (InvalidOperationException e)
            {
                throw new InvalidOperationException($"Cannot define multiple {nameof(ResourceAttribute)}s on type '{resourceType}'.", e);
            }
        }

        public string FormatPropertyName(PropertyInfo property) => ApplyCasingConvention(property.Name);

        public string ApplyCasingConvention(string properName) => properName.Camelize();
    }
}
```

and I registered it on `Startup.cs` constructor: `JsonApiOptions.ResourceNameFormatter = new CamelCaseResourceNameFormatter();`

and now all of my resources are camelized except for the route names

**Comment by maurei** [comment]
OK, it seems indeed that this is not properly supported.

I'm currently working on a pretty big rework of the serialization layer where all of this will be solved. It is expected to be merged with the v4 dev branch in a few days. Please hold on for a bit longer until we've made this one available.  Note that it will require you to migrate your application to V4. There is no guide yet with a comprehensive list of things you need to look after, but if you download the newest pre-release package from nuget and fix the build errors, you should be good to go.

**Comment by maurei** [comment]
@ahmadalli 
> and now all of my resources are camelized except for the route names and pagination links are referring to wrong path

What exactly is the output you're having and what is it you're expecting? Do you mean they're still in kebab-case and you had expected the links to be pascalCase as well?

**Comment by ahmadalli** [comment]
the routes remain kebab-case but the pagination links will use camelCase resource names which results in 404 error

**Comment by jaredcnance** [comment]
The routing convention is applied during service registration [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/c6762b399bca08712650b1ae2bf4b06d9da957a6/src/JsonApiDotNetCore/Extensions/IServiceCollectionExtensions.cs#L200) by the `DasherizedRoutingConvention`. At one point this was the accepted standard convention for json:api routing. As a quick hack you can disable the convention on a base class using `[DisableRoutingConvention]`:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/448114793a72e134f7720f436e34855df3532d32/src/JsonApiDotNetCore/Internal/DasherizedRoutingConvention.cs#L35-L37

Otherwise, you can inject your own `IApplicationModelConvention` which will provide your own routing convention. This should unblock you. From a project standpoint, it would probably be good if the routing convention matched the resource naming conventions by default.  This could be done by getting a name formatter here (the one challenge is you don't have access to the container in this scope):

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/448114793a72e134f7720f436e34855df3532d32/src/JsonApiDotNetCore/Internal/DasherizedRoutingConvention.cs#L25

**Comment by maurei** [comment]
>  From a project standpoint, it would probably be good if the routing convention matched the resource naming conventions by default.

I agree. But  I think we should generalise this further by adding the following rules:
1. by default, the relationship names in the body and url (route or query parameters) should match too
2. by default, the attribute names in the body and url (query parameters) should match too

So that would imply the following document with corresponding URLs:
```
/$TYPE/1?include=$RELATIONSHIP&field[$TYPE]=$ATTRIBUTE

{
  "data": {
    "type": "$TYPE",
    "id": "1",
    "attributes": {
      "$ATTRIBUTE": "JSON:API paints my bikeshed!"
    },
    "relationships": {
      "$RELATIONSHIP": {
          "data": null 
       },
       "links": {
          "self": "/$TYPE/1/relationships/$RELATIONSHIP",
        }
    }
  }
}

```

Additionally, to prevent inconsistent URLs like `my-models/1/relationships/myRelationship`, I would suggest to also add the rule
3. by default, apply the same casing convention to `$ATTRIBUTE`, `$RELATIONSHIP` and `$TYPE`.

Currently the official recommendation for $ATTRIBUTE and $RELATIONSHIP is `camelCase`. The default configuration with the rules outlined above would imply that the entire URL as well as the identifiers in the document body would be `camelCase`. 

I would propose to have this as the default configuration, and on top of that allow for an option to use `kebab-case` everywhere instead of `camelCase`.

Thoughts are welcome

**Comment by maurei** [comment]
New insight. This is relevant: https://github.com/json-api/json-api/issues/1091#issuecomment-543078469. For sparse field selection, if we stick to `field[$TYPE]=$ATTRIBUTE` as proposed in my previous comment, we would stuck with the constraint as described by the OP in the link above. 

We currently already support [sparse field selection on relationships](https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/436) and if we wish to keep on supporting this (which I think we should) we cannot go with `$TYPE` in the field selection because it would then be impossible to differentiate between `articles?fields[author]=firstName` and `articles?fields[reviewer]=lastName` (`author` and `reviewer` are both `people`).

Hence, updated proposal

```
GET /$TYPE/1?include=$RELATIONSHIP&fields=$ATTRIBUTE&fields[$RELATIONSHIP]=$ATTRIBUTE

{
  "data": {
    "type": "$TYPE",
    "id": "1",
    "attributes": {
      "$ATTRIBUTE": "JSON:API paints my bikeshed!"
    },
    "relationships": {
      "$RELATIONSHIP": {
          "data": null 
       },
       "links": {
          "self": "/$TYPE/1/relationships/$RELATIONSHIP",
        }
    }
  }
}
```

Note that this changes nothing with respect to normalizing the casing for `$ATTRIBUTE`, `$RELATIONSHIP` and `$TYPE`, because we would still want to avoid routes like `my-models/1/relationships/myRelationship`. About the latter: I'm making progress in configuring a `IApplicationModelConvention` with dependency injection, which would ultimately allow the developer to define a relationship between  `$ATTRIBUTE`, `$RELATIONSHIP` and `$TYPE` as occurring in the URL and body as they please.
