### ISSUE TITLE
Support for query parameters on nested/deep resource endpoints

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#627]
## Description
For example, the URL:

`https://localhost:5001/api/users/123/orders?fields[orders]=purchase-date`

returns all attributes of orders, instead of only purchase-date.

**Comment by maurei** [comment]
I think the malfunctioning of paging, inclusion and sparse field (and probably the rest of the query parameters too) for nested resources have a common origin. Thanks for pointing this out

**Comment by maurei** [comment]
I looked into this and unfortunately this is all pretty complicated

### Include
This was easy to support and is addressed in #634 

### Filter
Doing a filter on nested resource routes essentially the same as performing a [EF Core filtered include which is not possible](https://github.com/aspnet/EntityFrameworkCore/issues/1833). Eg the following request
```
GET /articles/1/tags?filter[name]=jsonapi
```
would be translated to the currently not supported EF Core invocation
```c#
dbContext.People.Include(e => e.Tags.Where(t => t.Name.Contains("jsonapi")));
```

### Paging

I suspect this is also not possible, see the following passage ([source](https://stackoverflow.com/a/32646709/4441216))
> Currently, in EF you cannot filter or limit the Included related entities in any way.

Note that this is about EF, but if it wasn't supported in EF that is a good indicator that it isn't supported in EF Core either. I need to research this further to be sure, but even if it turns out that EF Core works smoothly with it, the same issue as with sparse field selection and sorting will be encountered (next paragraph).

### Field selection, sorting
I think it is feasible to build expression trees that perform a sql `SELECT` and `ORDER` on the dataset, but this is currently not straight forward to implement due to design choice in JADNC. The problem is that the current expression tree building as performed in the `IResourceRepository<Article>` assumes that the table for which to perform a `SELECT`/`ORDER` is the "base" table of the query. This will not work for nested resource endpoints because it will always involve an `INNER JOIN`.

We could go ahead and change the expression tree building to be more flexible and support this. But from a separation-of-concerns point of view, I don't think having the `IResourceService<Article>` call `Select` and `Sort` methods on `IResourceRepository<Article>` to perform a select on or sort by operation for fields that are defined on `Tags` is a good way forward. To properly implement this we need to seriously detangle this.

#### Temporary work around: in-memory
Nevertheless: paging, field selection, sort and even included filtering can support in-memory to ensure consistency in the API response. I'm currently pretty busy with other stuff but this definitely is high up in the backlog. I think currently a developer could already implement this themselves by accessing [the query parameter services](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/wiki/v4/content/query-parameter-services.md) in a `OnReturn` and performing these operations himself

For now I have changed the API to be explicit about this not being supported by returning a HTTP 400 Bad Request for unsupported query parameters, see #634.

**Comment by bart-degreed** [comment]
First of all, thanks for putting effort in this. I can image these things are hard to get right. 

But I'm surprised (and concerned) to find out these nested scenarios were never supported. This is what I expected the library to excel in: auto-generating smart SQL queries over relationships in various directions with unconstrained depth, based on the model/graph. Not having these features makes me doubt whether adopting this library for us is even an option. 

I expected the library to translate a request to:
```
/articles/1/tags?filter[name]=jsonapi
```
into:
```
dbContext.Tags.Include(e => e.Article).Where(t => t.Article.Id.Equals(1) && t.Name.Equals("jsonapi"));
```
because `tags` is the primary data source in this request, just filtered by something related. This is semantically the same as:
```
/tags?filter[article.id]=1&filter[name]=jsonapi
```
and I expected the library to generate the same SQL statement for both of them.

I am not interested in the proposed in-memory workaround. And would recommend against it, because it creates false expectations. Better not have it, than remove it in vNext because it was never properly implemented and upset existing users.

I get that you are trying to finalize for the v4 release and a change like this involves a lot of effort and causes risk. However if this remains unsupported, it would help others to mention these limitations in the documentation.

**Comment by maurei** [comment]
Currently the library identifies `Article` as the primary data source for that request, which means the outer query is on `Article` instead of `Tag` (I do not know what the creators design consideration was to choose `Article instead of `Tag`). That means that the current query would look like

```c#
db.Article.Include(a => a.Tags).Where(a => a.Id.Equals(1) &&  a.Tags.Where( t => t.Name.Equals("jsonapi")));
```
Which is a bit more tedious to build with expression trees, and rapidly becomes unmanageable filtering on deeper included resources.

I think if we were to identify `Tag` as the primary request resource, building the expression tree as in the example you gave will be significantly easier, and we should even be able to support nested filters on endpoints like this

```c#
/articles/1/tags?include=blogs&filter[articleType]=1&filter[blog.Type]=2
```

Unfortunately this is still not a small fix: treating `Tag` as the main resource instead of `Article` will require some work on this particular pipeline, but it should be manageable. But we would be staying away from excessively complex expression tree-building  [as these guys must have been doing](https://github.com/aspnet/EntityFrameworkCore/issues/1833#issuecomment-81505343) which I believe is currently beyond the scope of JADNC

I will further scope the size of this task in the course of this/next week

**Comment by bart-degreed** [comment]
I've been thinking about this some more and did some experiments. I discovered that my expectations on relationships of unconstrained depth were based on wrong assumptions and me not understanding the full story.

I found that relationship requests only go one level deep at most. So there is no such thing as `/users/1/orders/2/lines`. And there does not need to be, because it means the same as `/orders/2/lines`.

I also realized that an endpoint like `/users/1/documents` is ambiguous in case the document resource contains both an owner and a creator of type user. Would it return all documents for owner 1, for creator 1, or would it return documents where the owner or creator is user 1? Therefore I believe that within our API implementation we should prefer the `/documents?filter[owner.id]=1` format.

Then I tried to patch up parts of the library to transform requests to `/users/1/orders` into `/orders?filter[user.id]=1`, but eventually gave up on that. There are too many changes needed at all levels and I don't truly understand most of the JADNC internals yet.

My current workaround for the deep paging/filtering limitations is to perform a HTTP redirect in cases like `/users/1/orders`. I have a working prototype, but need to flesh out more details before it can be turned into a generic solution.

**Comment by maurei** [comment]
Such redirect feature sounds like a very interesting feature to add. Feel free to hit me up on our gitter channel if you would like to have a more direct communication line with me to address questions about JADNC internals

**Comment by bart-degreed** [comment]
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/plan#filtered-include

**Comment by maurei** [comment]
> https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/plan#filtered-include

Oh jeez, that's interesting. We'll have to do a lot of refactoring and improvements once this lands

**Comment by bart-degreed** [comment]
Replaced by #751,
