### ISSUE TITLE
JsonApiException namespace issue

### ISSUE THREAD

**Issue by wisepotato** [json-api-dotnet/JsonApiDotNetCore#638]
The current `JsonApiException` is situated in the `JsonApiDotNetCore.Internal` namespace, it should be in the `JsonApiDotNetCore.Internal.Exceptions`, as we have a folder for that.

As discussed in #620, where we discussed that namespaces are a bit of a mess at the moment, we should take some time to correct this.

**Comment by bart-degreed** [comment]
As part of #714, I have added several custom exceptions that derive from JsonApiException, to help in properly building Error objects that are json:api spec compliant. For example, Title must contain a generic message, while Detail must be case-specific.

I moved JsonApiException and derived classes into a public namespace, so that custom implementations can throw them instead of creating error objects themselves (which is still possible, by the way). I also moved Error and related types into the public Models namespace and added missing fields to make then json:api compliant.
