### ISSUE TITLE
How to include nested EF entities in include

### ISSUE THREAD

**Issue by guillemsola** [json-api-dotnet/JsonApiDotNetCore#652]
## Description

I'm using AutoMapper as I expose through a `Resource` information that I take from several classes that require EF navigation. See `src.EntityTypeNameType.NameType.Code` in the mapping that I use..

```c#
 CreateMap<Model.EntityName, DTO.EntityName>()
    .ForMember(dest => dest.NameType,
        opts => opts.MapFrom(src => src.EntityTypeNameType.NameType.Code));
```

What happens is that with the `DefaultEntityRepository` I see only the base include is included unless I force it.

My idea is to override the `IQueryable<Entity> Include(...)` and create a Dictionary of the nested includes required that need to be loaded to query all the tables in the relationship.

This is more a design question or feature-request rather than a bug. Does it make sense the solution I'm planning?

btw, congrats for this project looks very nice! ;)

## Environment

- JsonApiDotNetCore Version: v3.1.0
- Other Relevant Package Versions: AutoMapper

**Comment by bart-degreed** [comment]
I'm looking for the exact same thing!

I need additional navigation properties to be loaded unconditionally because they are flattened in the JSON output. And then, depending on what is included in the query string, I need to also load them for related entities.

For now, I'm using something like this in my repositories:

```csharp
private bool DeepIncludeUser => _includeService.Get().Any(list => list.Any(attribute => attribute.RightType == typeof(User)));

public override IQueryable<Completion> Get()
{
    IQueryable<Completion> query = base.Get()
        .Include(completion => completion.ContentItem);

    if (DeepIncludeUser)
    {
        query = query
            .Include(completion => completion.Actor.UserOrganizations)
                .ThenInclude(userOrganization => userOrganization.Organization)
            .Include(completion => completion.Actor.NotificationPreferences);
    }
    else
    {
        query = query
            .Include(completion => completion.Actor);
    }

    return query;
}
```

**Comment by guillemsola** [comment]
@bart-degreed interesting your approach. 

I see you are including them at get level which I guess means it those are queried always that a `User` property is included.

FYR I'm including them only when an include parameter is present `public override IQueryable<Entity> Include(IQueryable<Entity> entities, string relationshipName)` 

Probably it will be good to mention this is the doc as how the framework creators thing could be a good approach.

**Comment by bart-degreed** [comment]
I have both conditional and unconditional. See the `DeepIncludeUser` property, which reads from the query string inclusion service.

**Comment by rachael-ross** [comment]
I've run across a scenario where I need the same capabililty as described above.

**Comment by maurei** [comment]
In v4, the internals of inclusion have changed a bit which should make custom inclusion easier. To adjust *which* relationships should be included for a given pipeline, it is probably easiest to override the `ApplyInclude` method [in the service layer](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/efc1ab7a369a50dfe67a967829a9010113e2b30f/src/JsonApiDotNetCore/Services/DefaultResourceService.cs#L259). To change the behaviour *how* a certain relationship should be included (eg map it to a different property or so), you should probably patch the [related logic in the repository layer](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/efc1ab7a369a50dfe67a967829a9010113e2b30f/src/JsonApiDotNetCore/Data/DefaultResourceRepository.cs#L286)

**Comment by maurei** [comment]
I could be of more help given a more concrete example

**Comment by bart-degreed** [comment]
The problem here is that these dependencies cross resource-specific services and repositories, so it cannot be solved in a good way at those levels.

Let me illustrate using an example. Consider the next models:

```csharp
public class User : Identifiable
{
    [Attr(isImmutable: true)] 
    [NotMapped] 
    public string DisplayName => Name.First + " " + Name.Last;

    public Name Name { get; set; }
}

public class Name // not exposed as resource, only database table
{
    public string First { get; set; }
    public string Last { get; set; }
}

public class Blog : Identifiable
{
    [HasOne]
    public User Author { get; set; }
}
```

When getting users, it fails with a `NullReferenceException` in `DisplayName` because the Name navigation property was not loaded. In this case, it must be loaded **unconditionally**. One solution, at first sight, would be to override `DefaultResourceRepository.Get()`:

```csharp
public class UserRepository : DefaultResourceRepository<User>
{
    public override IQueryable<User> Get() => base.Get().Include(user => user.Name);
}
```

That works for the /users endpoint. But getting /blogs?include=author will cause the `NullReferenceException` again. So now we need a **conditional** include in the blogs repository:
```csharp
public class BlogRepository : DefaultResourceRepository<Blog>
{
    public override IQueryable<Blog> Get()
    {
        if (QueryStringHasAuthorIncluded())
        {
            return base.Get().Include(blog => blog.Author.Name);
        }
        else
        {
            return base.Get();
        }
    }
}
```
I know there are other places we can do the inclusion, like the `DefaultResourceRepository.Include()` method or `DefaultResourceService.ApplyInclude()`, but that does not change my point. The problem is we need to duplicate the inclusion logic whenever a resource contains a User resource, or when a resource contains another resource that contains a User resource, etc.

The best way I think to deal with this is to indicate on the **resource itself** which EF navigation properties must be unconditionally loaded. And then have the framework dynamically add EF includes for them.

Something like this (but with a better name):
```csharp
public class User : Identifiable
{
    [Attr(isImmutable: true)] 
    [NotMapped] 
    public string DisplayName => Name.First + " " + Name.Last;

    [JsonApiAlwaysAutoLoad] // <-------
    public Name Name { get; set; }
}
```

**Comment by bart-degreed** [comment]
Can we reopen this issue (or create a new one) to track the work involved for my proposal?

**Comment by maurei** [comment]
I will get back at this tomorrow.

**Comment by maurei** [comment]
I think this could be solved using either:
- EF Core's lazy loading
- ResourceHooks as introduced in v4

#### Lazy loading
One way to approach this could be to configure EF Cores [lazy loading](https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading) for this relationship. I haven't tried this but it looks like it should work. As soon as the getter of the `Name` property is called, EF Core will populate the related data and it should avoid a `NullReferenceException` from occurring. That would happen as soon as `DisplayName` is parsed within the serialization layer

#### Resource hooks
When it comes to cross resource-specific services, a solution within the sphere of JANDC would be to use resource hooks. These are designed to execute business logic when requests involve nesting of an arbitrary deep level. 

In this case, implementing the `AfterRead` hook for `User` will enable you to access to a complete list of `User` instances involved in any get request, independent from which resource pipeline it is triggered, i.e.  `/users` or `/blogs?include=author` or even `/blogs?include=author.x.y.users.z.u.v.users`. That would look something like this:

```c#
public class UserDefinition : ResourceDefinition<User>
{
    private readonly AppDbContext _dbContext;
    public UserDefinition(IResourceGraph resourceGraph, AppDbContext dbContext) : base(resourceGraph)
    {
        _dbContext = dbContext;
    }

    public override void AfterRead(HashSet<User> entities, ResourcePipeline pipeline, bool isIncluded = false)
    {
        foreach (var user in entities)
        {
            _dbContext.Entry(user).Reference(u => u.Name).Load();
        }
    }
}
```

This would ensure the `Name` relationship is loaded for every `User` involved in the request before exiting the service layer.

Let me know if that helps

**Comment by bart-degreed** [comment]
Both solutions seem to depend on lazy loading, which is something I'm trying to prevent.

If I understand correctly, lazy loading would mean an additional query is executed for each resource property access, right? So getting a list of 100 users would execute 101 queries. That does not sounds appealing to me.

Aside from that, I've been ignoring resource hooks completely because I find them unusable as they are now. It's an all-or-nothing experience, and once enabled it would fetch an entire table instead of relying on paging, which is unacceptable in our case.

**Comment by bart-degreed** [comment]
Do you see any objections in my proposal?

**Comment by maurei** [comment]
> instead of relying on paging

 Better integration with paging is definitely desired, we need consider that carefully and work on that ([last mentioned here](https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/623#issuecomment-554941268)). Related: I shared some thoughts on [how we could improve hooks performance](https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/623#issuecomment-586015152).

> So getting a list of 100 users would execute 101 queries

This can be a single query using `Where()` + `Contains()` with some in-memory assignments which would be still fairly efficient (more so if we assume better paging-hooks integration). Still, the most optimal would indeed of course be using the principal query for that. 

From a technical point of view I think the approach is possible. It would involve building nested `ThenInclude()` expression trees in the repository or extending the `RelationshipAttribute`s   and create an additional relationship chain based on the `User` mode in the service layer. An architectural concern there is separation of concerns: the `Blog` pipeline would obtain complex responsibility for interacting with a resource being different than `Blog`. It shouldn't be responsible for loading `Name` onto `User`.

It calls for a separate service to take care such of cross-resource query additions. Probably would be a good reason to work on that [`IQueryable` hook](https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/623#issuecomment-558118322). Something like this would probably be the most favourable approach from an architectural point of view and would have a much wider range of applicability than just this use-case.
