### ISSUE TITLE
Make JsonApiDotNetCore ignore certain controllers

### ISSUE THREAD

**Issue by wayne-o** [json-api-dotnet/JsonApiDotNetCore#777]
## Description
Is there a way to have JsonApiDotNetCore ignore non-json-api controllers?

It seems to be based on the assumption that it owns the whole api now which wasn't the case previously. Is there a way to have a mix of controllers in the API?

...

## Environment

- JsonApiDotNetCore Version: 
- Other Relevant Package Versions:

**Comment by bart-degreed** [comment]
Actually, such isolation was buggy before, but fixed in https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/731/files#diff-14b27384f7f588d2fd504ae6e5102c0dR7-R11. There are some tests in the solution for a controller that returns strings instead of json, running side-by-side with json:api controllers.
