### ISSUE TITLE
PluralizedTypeName option when adding resource doesn't work for routing

### ISSUE THREAD

**Issue by vdaras** [json-api-dotnet/JsonApiDotNetCore#786]
## Description

Explicitly setting a pluralized type name for a resource doesn't work for routing purposes. Example:

```
var mvcBuilder = services.AddMvcCore();
services.AddJsonApi(options => {
    options.Namespace = "api/v1";
}, resources: resources => {
    resources.AddResource<TodoResource, Guid>(pluralizedTypeName: "todos");
});

services.AddScoped<IResourceService<TodoResource, Guid>, TodoResourceService>();
```

Controller is defined as follows

```
public sealed class TodoController : JsonApiController<TodoResource, Guid>
{
    public TodoController(
        IJsonApiOptions jsonApiOptions,
        ILoggerFactory loggerFactory,
        IResourceService<TodoResource, Guid> resourceService) 
    : base(jsonApiOptions, loggerFactory, resourceService)
    {
    }
}
```

But when trying to call the API it seems the respective controller is still registered at **/api/v1/todoResources** instead of **/ap1/v1/todos**

```
curl -I -X GET http://localhost:5001/api/v1/todos        
HTTP/1.1 404 Not Found
Date: Sun, 28 Jun 2020 19:14:46 GMT
Server: Kestrel
Content-Length: 0
```

```
curl -I -X GET http://localhost:5001/api/v1/todoResources
HTTP/1.1 200 OK
Date: Sun, 28 Jun 2020 19:13:15 GMT
Content-Type: application/vnd.api+json
Server: Kestrel
Transfer-Encoding: chunked
```

## Environment

- JsonApiDotNetCore Version: 4.0.0-alpha5
- Other Relevant Package Versions:

**Comment by vdaras** [comment]
The issue might be that the following code doesn't take into account pluralized type names when generating template for controller - but I'm not really sure since I'm not very familiar with the whole codebase

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/36bc4896a4072b0fe330fe69e65aed78ec6f573c/src/JsonApiDotNetCore/Internal/DefaultRoutingConvention.cs#L58

**Comment by bart-degreed** [comment]
Hi @vdaras,

Thanks for reporting this. It is unclear to me whether this is a bug or by design, but adding the next line on your controller may solve the problem (see documentation [here](https://json-api-dotnet.github.io/JsonApiDotNetCore/usage/routing.html)):

```c#
[Route("api/v1/todoResources"), DisableRoutingConvention]
```

**Comment by bart-degreed** [comment]
Or would it help to put [ResourceName("todos")] on your resource type?

**Comment by maurei** [comment]
I looked into this, you're right @vdaras: the `pluralizedTypeName` option from your example is ignored. 

The default routing convention aims to create a route template for every controller that matches the resource name as in the json payload, i.e. the `type: todoResources` member (which should then match `/todoResources`). 

Parallel to that, there is three ways to configure the resource name, in order of priority:
1.  the `pluralizedTypeName` option as you used in your example
2. `ResourceAttribute` on the model class
3.  do nothing: the resource type name will be transformed with a camelCase formatter.

Configuration through (1) is currently not accessible by the routing convention because it is stored on the resource graph, which is not injected in the routing convention. Right now we're only injecting the resource name formatters in the routing convention, which is not enough and also leads to some code duplication. I'm going to fix this.
