### ISSUE TITLE
How to serialize DateTime as Date on one object?

### ISSUE THREAD

**Issue by mkoppanen** [json-api-dotnet/JsonApiDotNetCore#796]
## Description

Most datetimes in the domain I have use default serialisation. However, things like DateOfBirth should be serialised as Date without time. It seems like JsonConverter attribute is ignored during serialisation. I guess it would be possible to work around this by using a custom type and adding global converter for the type but this seems like an overkill for such a simple issue.

...

## Environment

- JsonApiDotNetCore Version: 4.0.0-alpha5
- Other Relevant Package Versions:

**Comment by bart-degreed** [comment]
First a bit of background on what I think is going on here:
1. Newtonsoft.Json has [no builtin support](https://www.newtonsoft.com/json/help/html/DatesInJSON.htm) for Date serialization.
2. At a shared level, this can be accomplished by setting a [custom date format string](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_DateFormatString.htm), but there is no corresponding attribute.
3. To control this per attribute, a [custom converter](https://stackoverflow.com/questions/18635599/specifying-a-custom-datetime-format-when-serializing-with-json-net) is needed.

For example, the next code:
```c#
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var person = new Person
            {
                Name = "John Doe",
                DateOfBirth = new DateTime(2000, 1, 2),
                LastModifiedAt = DateTime.Now
            };

            var settings = new JsonSerializerSettings
            {
                Formatting = Formatting.Indented,
                DateFormatString = "yyyy-MM-dd \"at\" HH:mm"
            };
            
            string text = JsonConvert.SerializeObject(person, settings);
            Console.WriteLine(text);
        }
    }

    public class Person
    {
        public string Name { get; set; }
        
        [JsonConverter(typeof(DateFormatConverter))]
        public DateTime DateOfBirth { get; set; }

        public DateTime LastModifiedAt { get; set; }
    }

    public class DateFormatConverter : IsoDateTimeConverter
    {
        public DateFormatConverter()
        {
            DateTimeFormat = "yyyy-MM-dd";
        }
    }
}
```

produces:
```json
{
  "Name": "John Doe",
  "DateOfBirth": "2000-01-02",
  "LastModifiedAt": "2020-08-04 at 10:47"
}
```

The problem: when applying this on a resource in JADNC, the custom converter does not execute.

Unfortunately there is no easy fix for that, because property values are [copied](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/e0270bd3cd344ebb5ff99593cc2c96e54dd17218/src/JsonApiDotNetCore/Serialization/Common/ResourceObjectBuilder.cs#L155) into a temporary dictionary, which is later passed to Newtonsoft.Json. So while the *type* gets preserved (and any attributes on it), the *property* itself (and any attributes on it) is not.

**Comment by bart-degreed** [comment]
Another workaround would be to expose a calculated string property, like this:

```c#
public class Person : Identifiable
{
    [Attr("dateOfBirth")]
    public string JsonDateOfBirth
    {
        get => DateOfBirth.ToString("yyyy-MM-dd");
        set => DateOfBirth = DateTime.Parse(value).Date;
    }

    public DateTime DateOfBirth { get; set; }
}
```

**Comment by mkoppanen** [comment]
@bart-degreed,

thanks! the workaround works perfectly for the use case.

**Comment by bart-degreed** [comment]
Glad to help :)
