### ISSUE TITLE
Support spatial filter operators

### ISSUE THREAD

**Issue by bjornharrtell** [json-api-dotnet/JsonApiDotNetCore#809]
I think the operations from this list that are predicates would be relevant to support as filter operators:

https://docs.microsoft.com/en-us/ef/core/modeling/spatial

Most relevant are probably the ones that are supported by all providers for the geometry type:

* Contains
* Crosses
* Disjoint
* Intersects
* IsWithinDistance
* Overlaps
* Within

**Comment by bkoelman** [comment]
Closing, as this feature request has been open for a very long time. The JADNC team has no interest in implementing this, and no community members have expressed such interest either. Feel free to add a comment if you'd like to start working on this.

Also, since [v5.3.0](https://github.com/json-api-dotnet/JsonApiDotNetCore/releases/tag/v5.3.0) it should be possible to implement spatial operators outside of the JsonApiDotNetCore codebase.

**Comment by bkoelman** [comment]
Sounds good, thanks. When you get to it, can you try implementing them outside of the JADNC codebase? It should be possible now without depending on internals. It would be an excellent use case for the recently added extensibility. And given the limited interest, I'd prefer this be implemented as an external community addition, so the core team doesn't need to maintain it.

**Comment by bjornharrtell** [comment]
Yep sounds reasonable. 🙂
