### ISSUE TITLE
Allow externally setting Property for AttAttribute

### ISSUE THREAD

**Issue by bjornharrtell** [json-api-dotnet/JsonApiDotNetCore#814]
I will try to motivate why but it is a bit difficult to abstract out into a general simple use case.

What I have is something close to TPT recently completed for EF Core 5 preview 8 (https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-ef-core-5-0-preview-8/#table-per-type-tpt-mapping).

I simulate TPT in EF Core 3.1 by implementing the service layer for the "base class" with custom code, querying the "subclasses" from dbcontext dynamically based on a filter and mapping them to the "base class" entitty that has a set of properties that are common to all subclasses and the ones that vary are kept in a dictionary of string/object pairs an attribute on the base class. In the service I use bits an pieces from the generic implementation, for example I use the WhereClauseBuilder which when used relies on AttAttribute to resolve the attributes. I then "rewrite" FilterExpressions to remap from the dictionary to actual properties on the subclasses and in that process I need to recreate AttAttribute with the correct PropertyInfo that I find through reflection.

I realize this is perhaps a bit hacky/brittle approach to TPT but even when EF Core 5 lands we might not be able to rework out physical model to use that functionality, and it does actually seem to work pretty well in practice.

I've currently worked around this by setting the internal Property on AttAttrribute using reflection which does the trick but would like to avoid that.

**Comment by bart-degreed** [comment]
If I understand correctly, you want to change where `attr.Property` points to per request. That would break parallel request processing, as there is only one Attr per resource property that is shared between all requests. There is only one resource graph. The property is designed to be assigned once at the time the resource graph is built, functionally making it immutable and therefore safe for parallel processing. Breaking that contract likely has several implications throughout the library because it's assumptions are no longer true.

I'm not against opening this up, for example to alter the resource graph in a post-processing step before requests start being processed. But I think what you're trying to do here is not the right reason.

**Comment by bart-degreed** [comment]
If, on the other hand, your goal is to create temporary Attr objects that are not part of the resource graph (and not shared), this can be done by deriving from AttrAttribute where you add an extra PropertyInfo that holds your dynamically assigned value and overriding methods on QueryClauseBuilder to inspect your extra PropertyInfo to turn a chain of fields into a dotted property access expression. See CreatePropertyExpressionForFieldChain method.

**Comment by bjornharrtell** [comment]
@bart-degreed I agree the first example would be a bad idea. What I'm doing is more like the second example. I will investigate doing it through overrides.

**Comment by bjornharrtell** [comment]
@bart-degreed customizing by deriving like you propose works and while it is a bit more involved it is perhaps also the way to go for the use case. But, AttrAttribute is sealed. Shall I rework this PR to simply remove the seal for AttrAttribute and rename this PR to "Allow to derive from AttAttribute"?

**Comment by bart-degreed** [comment]
Do you need `AttrAttribute` specifically unsealed? Why not derive from `ResourceFieldAttribute` instead?

**Comment by bjornharrtell** [comment]
You are right. I wrongly assumed I would need the implementation in AttrAttribute.
