### ISSUE TITLE
JsonApiDotNetCore.Repositories.IDbContextResolver Error

### ISSUE THREAD

**Issue by bluedog13** [json-api-dotnet/JsonApiDotNetCore#830]
## Description
InvalidOperationException: Unable to resolve service for type 'JsonApiDotNetCore.Repositories.IDbContextResolver' while attempting to activate 'JsonApiDotNetCore.Repositories.EntityFrameworkCoreRepository`2

## Environment
- JsonApiDotNetCore Version:  4.0.0-beta1

I am not using EF Core at all - just a basic API that references a library project in the same solution.    I am very confused about the EntityFrameworkCoreRepository and it's need in the project(which I won't be using in the solution).

Please help in resolving this issue.

**Comment by bart-degreed** [comment]
Hi @bluedog13, `EntityFrameworkCoreRepository` is used by default as backing store by `JsonApiResourceService`. See [here](https://json-api-dotnet.github.io/JsonApiDotNetCore/usage/extensibility/layer-overview.html) for an overview.

If not using EF Core, you can replace the repository with a custom implementation of `IResourceRepository<TResource, TId>`, which is injected in the service. Or even replace the service layer too, by injecting your own service layer in controllers.

If you're stuck and need help, please share your controller/service classes (just the class and constructor signature should be enough) and any custom registrations for them you have in Startup.cs. It would even be better to share a repro-project so we can analyze what is going on.

**Comment by bluedog13** [comment]
Thanks for the reply and the link to the documentation.  It helped me understand more.   This below line of code (AddResourceService) in the snippet below resolved my issue.

.AddJsonApi(options =>
                {
                    options.DefaultPageSize = new PageSize(2);
                    options.IncludeTotalResourceCount = true;
                })
                .AddResourceService<WeatherForecastService>()

But what I am not seeing at the moment is - the response is in application/json format. 

My controller
public WeatherForecastController(IJsonApiOptions options,
            ILoggerFactory loggerFactory,
            IGetAllService<WeatherForecast> resourceService) : base(options, loggerFactory, resourceService)
        { }

My service
public class WeatherForecastService : IGetAllService<WeatherForecast>
    {....}

Is there anything else I need to add - to see the response in "application/vnd.api+json" format?

Thanks.

**Comment by bart-degreed** [comment]
Thanks, this clarifies a lot.

To enable JADNC serving resources, you need to add your resources to its graph. This can be done in three ways: automatically by providing an EF Core DbContext -or- automatically by scanning in an assembly -or- manually one-by-one by adding them to the graph as described [here](https://json-api-dotnet.github.io/JsonApiDotNetCore/usage/resource-graph.html#manual-specification).

The next thing is that your controllers need to derive from `JsonApiController<>` (or `BaseJsonApiController<>` if you have special routing requirements). Those require a generic type parameter, which tells JADNC which resource class they work with.

Finally, the framework registers an open generic for `IResourceService<>`, but since you're not using that you'll need to register the service yourself.

Example:

```c#
services.AddScoped<IGetAllService<WeatherForecast>, WeatherForecastService>();
```

Note your example uses `IGetAllService`, but that interface does not exist in JADNC without type parameters. Instead, we have `IGetAllService<TResource>` and `IGetAllService<TResource, TId>`.

There's an example in our codebase that shows how to use JADNC without entity framework at https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/src/Examples/NoEntityFrameworkExample. Hope this helps.

**Comment by bluedog13** [comment]
Thank you so much.  This resolved my issue and I am able to see the data as expected.  Thanks one again.

**Comment by bart-degreed** [comment]
Glad to hear this works for you now.
