### ISSUE TITLE
Paging does not work when not using EF Core

### ISSUE THREAD

**Issue by bluedog13** [json-api-dotnet/JsonApiDotNetCore#843]
## Environment
- JsonApiDotNetCore Version:  4.0.0-beta1
- Other Relevant Package Versions:

## Description

I am not using EF and have the below code snippet

In Startup.cs
```
.AddJsonApi(options: options =>
                    {
                        options.DefaultPageSize = new PageSize(2);
                        options.MaximumPageSize = new PageSize(5);
                        options.MaximumPageNumber = new PageNumber(2);
                        options.IncludeTotalResourceCount = true;
                    },
                    resources: builder => builder.Add<WeatherForecast>("weatherForecast"))
                .AddScoped<IGetAllService<WeatherForecast>, WeatherForecastService>()
```

At the Controller level
```
public class WeatherForecastController : BaseJsonApiController<WeatherForecast>
{....}
```

At Service level
```
public class WeatherForecastService : IGetAllService<WeatherForecast> {....}
```

I am not able to see the paging/total count being displayed in the response.  I see all the items being returned back.  I am hoping that JSON:API will be doing the paging and I am not required to have any paging logic.  This is the same project code base referred in issue #830 

Please help.

**Comment by bart-degreed** [comment]
When using EF Core, included relationships, paging, sorting, filtering and sparse fieldsets are all translated into SQL. So this is handled at the repository layer. The built-in service layer just collects query string parameters and passes them along. If you're building your own service (for example, because it fetches data using gRPC instead of SQL), you'll need to adapt the query string parameter values to the paging mechanism they provide. There is no in-memory implementation for filtering/paging/sorting in JADNC because it does not scale on large datasets.

Assuming your external data source provides a paging mechanism, see `JsonApiResourceService` for how to get the paging parameters from query string (the registered *QueryStringParameterReader classes). A heads-up though: if you're not using the built-in service/repository, that means there's a lot you'll need to implement by yourself...

**Comment by maurei** [comment]
Curious to know: what are you using for your data layer?

**Comment by bluedog13** [comment]
Thanks for the replies.  In my case,  it can either be MongoDB/Cassandra or Aerospike - not sure at the moment.

**Comment by maurei** [comment]
If you're planning on seriously looking into tying together the `JsonApiResourceService` layer with a custom nosql `IResourceRepository` implementation, please keep me in the loop. Eventually this is something we would like to support in JADNC.

**Comment by bart-degreed** [comment]
Closing, as the question has been answered.
