### ISSUE TITLE
Include Query Error Not Working

### ISSUE THREAD

**Issue by mdhthahmd** [json-api-dotnet/JsonApiDotNetCore#861]
Hi, i am trying to implement many-to-many and one-to-many relationships in this library, so i followed the code samples and documentation but i am unable to get the include query working,
For example when i ran the provided example project which has the many-to-many relationship between Articles and Tags,
GET /articles works and return the correct response, while GET /articles?include=tags return 500 error.
It looks like any resource that has to many relationship does not work, with the provided example and documentation. So what is the intended way of implementing to-many relationships?

**Comment by bart-degreed** [comment]
Hi @mdhthahmd, which version of JsonApiDotNetCore are you using? I'm asking because it should work. We have various usages in tests, for example [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/6f72110fcc78939567dc0a444e70fc62fe3bb26a/test/JsonApiDotNetCoreExampleTests/IntegrationTests/Includes/IncludeTests.cs#L314).

Assuming you're using a recent 4.x prerelease version, it would help to include the error message you're getting (with stack trace) or post some code to reproduce the problem.

**Comment by mdhthahmd** [comment]
Hi @bart-degreed, i just cloned the repo and got started today, so current master/main branch.
Ok, i will provide the error message soon

**Comment by bart-degreed** [comment]
I've verified this on master and you're correct this does not work. Unfortunately it is caused by [a bug in EF Core](https://github.com/dotnet/efcore/issues/21026). You can help us by upvoting that issue.

As a workaround, you can disable paging:
```c#
options.DefaultPageSize = null;
```
in JsonApiDotNetCoreExample.Startup.ConfigureJsonApiOptions method.

That makes the request succeed, but still fails when paging at both levels is explicitly asked for:

```http
http://localhost:14140/api/v1/articles/?include=tags&page[size]=1,tags:1 HTTP/1.1
```

**Comment by mdhthahmd** [comment]
Hi @bart-degreed , the work around ```options.DefaultPageSize = null;``` do return a proper response, but the include is missing of the response and data of the root resource is empty.

**Comment by mdhthahmd** [comment]
Ok, i finally found out the cause, i was using sqlite and the error is reproducible, when i switched to sqlserver the feature works as intended, so i am geussing this has something to do with sqlite provider for efcore @bart-degreed
