### ISSUE TITLE
How to filter IResourceService<TResource> when using Dapper (without EF)

### ISSUE THREAD

**Issue by lrfahmi** [json-api-dotnet/JsonApiDotNetCore#867]
## Description
I created resource service `public class ProductService : IResourceService<Product>`.

```
public async Task<IReadOnlyCollection<Product>> GetAsync()
{
    using IDbConnection connection = GetConnection();
    return await connection.QueryAsync<Product>("SELECT * FROM dbo.Product");
}
```
When i filter on request `http://localhost:5000/api/v1/products?filter=equals(name,'Software')` return as not filtered. How to apply filter for this case?
...

## Environment

- JsonApiDotNetCore Version: 4.0.0-beta1
- Other Relevant Package Versions:

**Comment by bart-degreed** [comment]
Hi, @lrfahmi,

The high-level query pipeline we use for EF Core is described at https://json-api-dotnet.github.io/JsonApiDotNetCore/internals/queries.html.

You can jump in at any point and replace or reuse the implementations, depending on your needs. The parsed filter in query string is accessible through `IFilterQueryStringParameterReader.GetConstraints()`. You can take that directly, or reuse `IQueryLayerComposer`, which gathers all parsed query string parameters and builds a `QueryLayer` (which is our own internal, intermediate representation of the request) and go from there.

Translation to SQL is something you'll need to handle yourself, obviously, as you're using Dapper. Depending on what you'd like to support, this can become quite complex. Our translation from the internal query tree into EF Core queries is in the `JsonApiDotNetCore.Queries.Internal.QueryableBuilding` namespace, it case it helps.

**Comment by lrfahmi** [comment]
Thanks for the explanation. I think it's very complex. I hope this repo can be integrated with Dapper in the future.

Now I will first use EF for this my case. Thank you very much.

**Comment by bart-degreed** [comment]
From what I understand, Dapper is the preferred choice for specific scenarios where putting extra work in tweaking the SQL by hand is justified, because it is a hot code path and the specific scenario allows for optimizations that generic tools cannot know. 

Therefore I don't think having JsonApiDotNetCore rely on Dapper for its general-purpose query generation is a good fit. We would basically need to build what EF Core already provides, without having more information that would enable us to generate better SQL statements.
