### ISSUE TITLE
Slow Query Performance on get with relationships

### ISSUE THREAD

**Issue by TarllesRoman** [json-api-dotnet/JsonApiDotNetCore#923]
#### DESCRIPTION

When I try execute a get request on a resource that have more than 1 relationship, entity framework gives me the following warning

Microsoft.EntityFrameworkCore.Query[20504]
      Compiling a query which loads related collections for more than one collection navigation either via 'Include' or through projection but no 'QuerySplittingBehavior' has been configured. By default Entity Framework will use 'QuerySplittingBehavior.SingleQuery' which can potentially result in slow query performance. See https://go.microsoft.com/fwlink/?linkid=2134277 for more information. To identify the query that's triggering this warning call 'ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning))'

In fact it has a slow performance, getting 30 seconds more to complete the request

#### STEPS TO REPRODUCE

My source code is like the code below

public class Pais : Identifiable {
  ...
 [HasOne]
 public Continente Continente { get; set; }

 [HasMany(PublicName = "ufs")]
 public ISet<UF> UFs { get; set; }
}

[HttpReadOnly]
public class PaisController : JsonApiController<Pais>
{
    public PaisController(IJsonApiOptions options, ILoggerFactory loggerFactory, IResourceService<Pais, int> resourceService) : base(options, loggerFactory, resourceService)
      { }
}

#### EXPECTED BEHAVIOR
Execute SQL query faster

#### VERSIONS USED
- JsonApiDotNetCore version: 4.0.1
- ASP.NET Core version: 3.1
- Entity Framework Core version: 5.0.0
- Database provider: SqlServer

**Comment by bart-degreed** [comment]
Hi @TarllesRoman,

Thanks for letting us know. Query splitting is one of the new features in EF Core 5. We've run our existing test suite against EF Core 5, but haven't done any work yet to support its new features.

It turns out you can influence this behavior via your connection string, as described [here](https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries#enabling-split-queries-globally).

Having said that, 30 seconds to execute a query sounds extremely slow to me. Are you fetching a massive amount of data or querying a large table without indexes? I would recommend to capture the SQL being produced and analyze its execution plan.

**Comment by TarllesRoman** [comment]
Hi

I turned out that slow behavior was caused by my PC, when I moved SQLServer to an external server instead run locally, it's solved itself...

To supress the warning I overwrote the GetAsync method to include .QuerySplittingBehavior only in this query, once influence behavior via connection string is impracticable because it influence all queries even those that dont need that

So, I'll close this issue expecting that in future versions you can include support to EF Core 5

Thanks by the help

**Comment by bart-degreed** [comment]
I suspect overriding `GetAll` would be more appropriate, because then it is also applied when fetching as part of updating relationships.
