### ISSUE TITLE
Pagination Links not forming correctly after hosting on IIS

### ISSUE THREAD

**Issue by Priyankadhavale** [json-api-dotnet/JsonApiDotNetCore#948]
#### DESCRIPTION

After hosting the JANDC used application on IIS, the pagination links generated by JANDC does not contain the application name in URL 

#### STEPS TO REPRODUCE

I have tried adding the my application under Default site 

so my URL forms like 
https://[ip address]/api/v1/articles?page[size]=10&page[number]=2 

So whenever I am accessing this URL => I am not able to get the result

Actual URL 

https://[ip address]/[applicationName]/api/v1/articles?page[size]=10&page[number]=2 

#### EXPECTED BEHAVIOR

Can you please let me know if we can achieve this with JANDC and how we can achieve this.

#### ACTUAL BEHAVIOR
Right now the base path that means https://<ip address>: <port> this much only added to pagination links in Links section of result.

#### VERSIONS USED
- JsonApiDotNetCore version: 4.0.0-beta1
- ASP.NET Core version:3.1
- Entity Framework Core version:3.1.10
- Database provider:SQL server

**Comment by bart-degreed** [comment]
Hi @Priyankadhavale, thanks for reporting this.

Its been many years ago since I last used IIS and its not something I can easily repro/debug. However, I can give you some pointers where to put breakpoints so you can analyze this yourself.

The IJsonApiRequest.BasePath is set here:
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/431541e4f9488af549efdc0d1496daec93e2a882/src/JsonApiDotNetCore/Middleware/JsonApiMiddleware.cs#L173

Which is then used to render paging/self links here:
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/431541e4f9488af549efdc0d1496daec93e2a882/src/JsonApiDotNetCore/Serialization/Building/LinkBuilder.cs#L108


Maybe some of the suggestions [here](https://stackoverflow.com/questions/58840424/retrieve-iis-applicationname-in-asp-net-core-3-application) help in finding a way to obtain the IIS application name.

Hope that helps!

**Comment by Priyankadhavale** [comment]
Hi @bart-degreed ,

Thanks for quick response. 

I have seen the code and in GetBasePath() method the following code is not adding httpRequest.PathBase (gives application name on iis ) string to builder because of that I can only see the URL till "http://[ip-address]" 
if (!options.UseRelativeLinks)
            {
                builder.Append(httpRequest.Scheme);
                builder.Append("://");
                builder.Append(httpRequest.Host);
            } 

Can you please suggest on this

Thanks,
Priyanka

**Comment by bart-degreed** [comment]
I think you're on the right track with PathBase (explanation [here](https://stackoverflow.com/questions/58614864/whats-the-difference-between-httprequest-path-and-httprequest-pathbase-in-asp-n)).

Things that come to mind:
- how can we write an integration test for this?
- how does this affect the `GetCustomRoute` method? (used for `[Route("some/path/to/articles")]` on controllers)

Looks like I'll need to setup IIS after all, to try these things out. At the moment, other work has higher priority. Is this something you need soon or can it wait some time?

In the mean time, can you work around this by hosting at the IIS root instead of from an application virtual directory?

**Comment by Priyankadhavale** [comment]
Hi @bart-degreed ,

We are using JANDC package in our application and we have release in next month. Is it possible that we can get fix for this till mid of March 2021.

And in the mean time we are trying to use this by hosting on IIS root instead of application virtual directory. There the URL is forming correctly.

Thanks,
Priyanka

**Comment by bart-degreed** [comment]
I cannot make hard promises but I intend to help you. Does #953 fix the problem?

**Comment by bart-degreed** [comment]
Fixed in [v4.0.4](https://github.com/json-api-dotnet/JsonApiDotNetCore/releases/tag/v4.0.4).
