### ISSUE TITLE
How to set up the models when the primary key is other than the default Identifiable Id

### ISSUE THREAD

**Issue by fgm1477** [json-api-dotnet/JsonApiDotNetCore#963]
#### DESCRIPTION

How to set up the models when the primary key is other than the default Identifiable Id

#### STEPS TO REPRODUCE

Ex.

Model

  public class Condition : Identifiable
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Attr()]
        public int ConditionID { get; set; }
        [Attr()]
        public string ConditionCode { get; set; }
        [Attr()]
        public string ConditionName { get; set; }   
    }

The route /api/conditions/1 

Error
{
  "errors": [
    {
      "id": "2d8a466b-e2dc-4ffa-a98d-b125bbfbee65",
      "status": "500",
      "title": "An unhandled error occurred while processing this request.",
      "detail": "The LINQ expression 'DbSet<Condition>()\r\n    .Where(c => c.Id == __Create_Item1_0)' could not be translated. Additional information: Translation of member 'Id' on entity type 'Condition' failed. This commonly occurs when the specified member is unmapped. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information."
    }
  ]
}

_Consider to include your code here, such as models, DbContext, controllers, resource services, repositories, resource definitions etc._

1. 
2. 
3. 

#### VERSIONS USED
- JsonApiDotNetCore version: 4.0
- ASP.NET Core version: 5.0
- Entity Framework Core version:  5.0.3
- Database provider: SQL server

**Comment by bart-degreed** [comment]
If with "other than the default" you mean a different _type_, use Identifiable that takes a type parameter (example [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/745d2fb6b6c9dd21ff794284a193977fdc699fe6/test/JsonApiDotNetCoreExampleTests/IntegrationTests/Links/Photo.cs#L9)).

If you intend to use a different _column name_ in the database, just use the regular [EF Core mapping capabilities](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties). So you can use either its fluent API for that:

```c#
public class AppDbContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        builder.Entity<Condition>(entity =>
        {
            entity.HasKey(entity => entity.Id);

            entity.Property(entity => entity.Id)
                .HasColumnName("ConditionID");
        });
    }
}
```

or use inline attributes. You can override the Id property to add extra attributes on it, such as in [this example](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/745d2fb6b6c9dd21ff794284a193977fdc699fe6/test/JsonApiDotNetCoreExampleTests/IntegrationTests/ModelStateValidation/SystemDirectory.cs#L12-L14).

The whole point of having the `Identifiable` base class is to provide a glue between json:api id (string) and the database primary key column. So trying to use _something else_ as primary key will break things. The error you're getting is because EF Core considers a property named 'Id' to be the primary key by default, but your annotations tell EF Core to deviate from that. So our code that assumes 'Id' is the key property to use in queries fails.

**Comment by fgm1477** [comment]
But now I'm getting another error when the Id is equal zero. My Id is not an identity and can be zero
How do I avoid the error below when the Id is equal to zero. I'm getting that when the controller is about to serialize the response.

{
    "errors": [
        {
            "id": "b478914e-ff82-4747-b1bf-6b893d8dc0c4",
            "status": "500",
            "title": "An unhandled error occurred while processing this request.",
            "detail": "Value cannot be null. (Parameter 'id')"
        }
    ]
}

**Comment by fgm1477** [comment]
I just figure out.

I overrode the method 
protected virtual string GetStringId(TId value);

 protected override string GetStringId(int value)
        {
            if (value == 0)
            {
                return "0";
            }
            return base.GetStringId(value);
        }

**Comment by maurei** [comment]
Consider using `int?` as a primary key. This scenario is supported without having to do additional overrides. [Click to see a working test case](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/47fdaa9ac4186bb8af921a6c1be99378e8923c06/test/JsonApiDotNetCoreExampleTests/IntegrationTests/ZeroKeys/ZeroAsKeyTests.cs#L36)

**Comment by fgm1477** [comment]
yes
