### ISSUE TITLE
Separate read and write contexts?

### ISSUE THREAD

**Issue by wayne-o** [json-api-dotnet/JsonApiDotNetCore#975]
Hi

How hard would it be to accomplish this? Can it be done as is or would I need to look at submitting a PR?

**Comment by bart-degreed** [comment]
We have an example project that registers and uses two DbContext types (different data models) at https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/src/Examples/MultiDbContextExample. This assumes you have two repositories: one for reads and one for writes.

Alternatively, there is `IJsonApiRequest.IsReadOnly` you can inject and use. This is intended for a single DbContext (single data model) and single repository, where you can dynamically read from a replica (different connection string) to handle high load.

**Comment by wayne-o** [comment]
Could this not be something that can be offered through the initialisation API? I’d be up for giving it a stab if it’s not too deep into the internals? I’d imagine it’d be quite easy no?

**Comment by bart-degreed** [comment]
There is an [overload](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/JsonApiDotNetCore/Configuration/ServiceCollectionExtensions.cs#L24) of `AddJsonApi` that takes multiple DbContexts if that's what you're looking for.

Perhaps if you explain what you're trying to accomplish I can provide better feedback.

**Comment by wayne-o** [comment]
I would just like to have a separate DBContext for GET and [POST/PATCH/DELETE/PUT]

That way I can use my read replicas for GET and the main PG servers for writes.

Something like `services.AddJsonApi<AppDbContextRead, AppDbContextWrite>`

Does that make sense? I think it should be fairly simple since it's by VERB

**Comment by wayne-o** [comment]
I think the way to do it as it stands is to provide a `IResourceReadRepository` per resource that needs to take advantage of the read replicas - I can provide just a `IResourceReadRepository` and the framework will use the defaults for the read yes?

**Comment by bart-degreed** [comment]
`IResourceReadRepository` is not intended for accessing a read-only data source, it just represents a set of read operations. Likewise, `IResourceWriteRepository` represents write operations, independent of the underlying data source. The problem is that when reading _as part of a write operation_, it should not use the read-only database.

I think you can accomplish this without modifications to JADNC. There are two ways to do this:
1. Use a single AppDbContext (assuming the models are identical), then within your repository check `IJsonApiRequest.IsReadOnly` and use a different connection string.
2. Use two DbContexts and inject them both into your repository. Then depending on `IJsonApiRequest.IsReadOnly`, direct calls to one or the other.

**Comment by wayne-o** [comment]
OK that sounds good - a bit of boilerplate code but I can live with that - so I will need to inject in `IJsonApiRequest` to my EntityFrameworkCoreRepository?

**Comment by wayne-o** [comment]
Oh hang on - that also means having 2 separate resources and 2 separate endpoints for the readonly bits?

**Comment by wayne-o** [comment]
Or is `IsReadOnly` set for GET requests?

**Comment by bart-degreed** [comment]
Yes it is.

**Comment by wayne-o** [comment]
Got this working :)
