### ISSUE TITLE
How can navigate HasOneAttribute to class property without "withForeignKey" parameter

### ISSUE THREAD

**Issue by Dusan-Hanecak** [json-api-dotnet/JsonApiDotNetCore#984]
#### DESCRIPTION

I would like upgrade JADNC from "v4.0.0-alpha4" to "v4.0.4"

Previous version "v4.0.0-alpha4" has got relationship attribute "HasOneAttribute" 
with navigation property "withForeignKey".

How can I do it into version "v4.0.4" ?
Where can I find more information ?

I would like fill attribute "Type" with value from relationship.
I used property "IdentifiablePropertyName" [from HasOneAttribute ]
for access to main object property.

#### STEPS TO REPRODUCE

POST/PUT/PATCH request

/api/projects

<pre>
{
  "data": {
    "type": "projects",
    "attributes": {
      "name": "test project"
    },
    "relationships": {
      "project-type": {
        "data": {
          "type": "project-types",
          "id": "245470c1-d5a1-4304-bb5b-b8e6a0b26872"
        }
      }
    }
  }
}
</pre>

1. "v4.0.0-alpha4"
<pre>
 public class ProjectModel : Identifiable< Guid >
 {               
        [Attr("name")]
        public string Name { get; set; }

        [Attr("type")]
        public Guid? Type { get; set; }

        [HasOne("project-type", withForeignKey: "Type")]
        public ProjectTypeModel ProjectType { get; set; }
}
</pre>

#### EXPECTED BEHAVIOR
after Deserialize input data

{
"name" : "test project",
"type" : "245470c1-d5a1-4304-bb5b-b8e6a0b26872"
}

#### ACTUAL BEHAVIOR
after Deserialize input data

{
"name" : "test project",
"type" : null
}

#### VERSIONS USED
- JsonApiDotNetCore version: 4.0.4
- ASP.NET Core version: 3.1
- Entity Framework Core version: NO Entity Framework
- Database provider: MSSQL

**Comment by bkoelman** [comment]
`withForeignKey` was removed because JADNC no longer needs this information. It now re-uses the mappings from EF Core instead. Use `[ForeignKey(name)]` if you're using a non-default key name, see [here](https://www.learnentityframeworkcore.com/configuration/data-annotation-attributes/foreignkey-attribute). If you're not using EF Core, please share your data access code (preferably a full repro project) so I can help you adapt.

**Comment by Dusan-Hanecak** [comment]
I do not like EF so much :)

In my opinion "withForeignKey" was very good feature for deserialization input object data for NON EF access.

Into version 2.0.8 it was done through
<pre>
var entityProperty = entityProperties.FirstOrDefault(p => p.Name == $"{attr.InternalRelationshipName}Id");
</pre>

Into version 3.1.0 and 4.0.4aplha  it was more flexible without strict name convension.
<pre>
        /// <summary>
        /// The independent resource identifier.
        /// </summary>
        public string IdentifiablePropertyName => string.IsNullOrWhiteSpace(_explicitIdentifiablePropertyName)
            ? JsonApiOptions.RelatedIdMapper.GetRelatedIdPropertyName(InternalRelationshipName)
            : _explicitIdentifiablePropertyName;

var foreignKeyProperty = entityProperties.FirstOrDefault(p => p.Name == attr.IdentifiablePropertyName);
</pre>

<hr>

I continue migration into "v4.0.4"

I added property "IdentifiablePropertyName" into "HasOneAttribute".

I read a list of relationship from "TargetedFields.Relationships"
and set appropriate attribute to myself.


I hope JADNC team will always support non EF access as well  :)

Thanks.

dus@N

**Comment by bart-degreed** [comment]
Hi @Dusan-Hanecak,

We fully intent to support non-EF Core usage, and because of that we better separated layers in v4.x. The consequence of not using EF Core means you'll need to do things yourself that come out-of-the-box otherwise (but should still be possible to add).

We took out `RelatedIdMapper` because it was a static property, which makes it hard to test and we felt the indirection was not very useful in general. Furthermore, exposing the foreign key name (which is relational database terminology) in the json:api resource classes does not fit well with the separation of layers. For example, MongoDB does not have the concept of foreign keys. Lastly, EF Core does not require to declare Id properties for foreign keys (see [shadow properties](https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties)), so JADNC should not assume they even exist. 

Therefore we moved dealing with foreign keys down to the repository layer. This means that middleware, action filters, serialization, controllers and resource services no longer have knowledge of or depend on them. This promotes reuse of components when not using EF Core.

To illustrate, our pipeline is: Middleware -> Serializer -> Controller -> Resource Service -> Resource Repository

where only _Resource Repository_ interacts with EF Core (and can be replaced independently).

Your approach to set the foreign key property on resource objects from within your custom repository sounds like the right solution to me.

I'm closing this, as you seem to have found a solution. Please feel free to let us know if you need anything else.
